# system:     "Makefile to run all tests, examples and tools"
# compiler:   "ISE Eiffel"
# author:     "Eric Bezault <ericb@gobosoft.com>"
# copyright:  "Copyright (c) 2000-2001, Eric Bezault and others"
# license:    "Eiffel Forum Freeware License v1 (see forum.txt)"
# date:       "$Date$"
# revision:   "$Revision$"


ECOMPILER=ise

include ${GOBO}/misc/platform.mk
include ${GOBO}/test/all/common/test_all.mk
