# system:     "Makefile template for Eiffel compilations"
# author:     "Eric Bezault <ericb@gobosoft.com>"
# copyright:  "Copyright (c) 2000, Eric Bezault and others"
# license:    "Eiffel Forum Freeware License v1 (see forum.txt)"
# date:       "$Date$"
# revision:   "$Revision$"


# SmallEiffel
SE_COMPILER=compile
SE_CFLAGS=-boost -no_split -no_style_warning -no_gc $(SE_PCFLAGS)
SE_DEBUG_CFLAGS=-all_check -no_split -no_style_warning -no_gc $(SE_PCFLAGS)

# ISE Eiffel
ISE_COMPILER=es4
ISE_FINISH_FREEZING=finish_freezing
ISE_CFLAGS=-batch -finalize
ISE_CODEGEN=F_code
ISE_FFLAGS=$(ISE_PFFLAGS)
ISE_DEBUG_CFLAGS=-batch
ISE_DEBUG_CODEGEN=W_code
ISE_DEBUG_FFLAGS=$(ISE_PFFLAGS)

# Halstenbach
HACT_COMPILER=ibcomp
HACT_FISH=fish
HACT_CFLAGS=-executable -finalize -new -stop
HACT_CODEGEN=F_code
HACT_FFLAGS=
HACT_DEBUG_CFLAGS=-executable -new -stop
HACT_DEBUG_CODEGEN=W_code
HACT_DEBUG_FFLAGS=

# Visual Eiffel
VE_COMPILER=vec
VE_CLEANUP=vec -eu -y -no
VE_CFLAGS=-no
VE_DEBUG_CFLAGS=-no


all: help

depend: ise.dep hact.dep

help:
	@echo "make [ se[-debug] | ise[-debug] | hact[-debug] | ve[-debug] ]"

se: loadpath.se
	$(SE_COMPILER) $(SE_CFLAGS) -o $(TARGET) $(ROOT_CLASS) $(CREATION_ROUTINE)

se-debug: loadpath.se
	$(SE_COMPILER) $(SE_DEBUG_CFLAGS) -o $(TARGET) $(ROOT_CLASS) $(CREATION_ROUTINE)

ise: ise.ace
	$(ISE_COMPILER) $(ISE_CFLAGS) -ace ise.ace
	cd EIFGEN && cd $(ISE_CODEGEN) && $(ISE_FINISH_FREEZING) $(ISE_FFLAGS)

ise-debug: ise-debug.ace
	$(ISE_COMPILER) $(ISE_DEBUG_CFLAGS) -ace ise-debug.ace
	cd EIFGEN && cd $(ISE_DEBUG_CODEGEN) && $(ISE_FINISH_FREEZING) $(ISE_FFLAGS)

hact: hact.ace
	$(HACT_COMPILER) $(HACT_CFLAGS) -ace hact.ace -project $(TARGET).eif
	cd $(TARGET)_gen && cd $(HACT_CODEGEN) && $(HACT_FISH) $(HACT_FFLAGS)

hact-debug: hact-debug.ace
	$(HACT_COMPILER) $(HACT_DEBUG_CFLAGS) -ace hact-debug.ace -project $(TARGET).eif
	cd $(TARGET)_gen && cd $(HACT_DEBUG_CODEGEN) && $(HACT_FISH) $(HACT_DEBUG_FFLAGS)

ve: ve.esd
	$(VE_COMPILER) $(VE_CFLAGS) -a:ve.esd
	$(VE_CLEANUP)

ve-debug: ve.esd
	$(VE_COMPILER) $(VE_DEBUG_CFLAGS) -a:ve.esd
	$(VE_CLEANUP)

loadpath.se: $(ROOT_DIR)/loadpath.se
	$(CP) $(ROOT_DIR)/loadpath.se loadpath.se

include ise.dep

ise.ace: $(ROOT_DIR)/ise.tpl
	$(ECHO) "-- *** GENERATED BY 'make ise.ace' *** --" > ise.ace
	$(GEPP) $(ROOT_DIR)/ise.tpl - >> ise.ace

ise-debug.ace: $(ROOT_DIR)/ise.tpl $(ISE_CLUSTERS)
	$(ECHO) "-- *** GENERATED BY 'make ise-debug.ace' *** --" > ise-debug.ace
	$(GEPP) -DASSERTION $(ROOT_DIR)/ise.tpl - >> ise-debug.ace

ise.dep:
	$(ECHO) "ise.ace: $(GOBO)/library/kernel/ise.ace" > ise.dep

include hact.dep

hact.ace: $(ROOT_DIR)/hact.tpl
	$(ECHO) "-- *** GENERATED BY 'make hact.ace' *** --" > hact.ace
	$(GEPP) $(ROOT_DIR)/hact.tpl - >> hact.ace

hact-debug.ace: $(ROOT_DIR)/hact.tpl
	$(ECHO) "-- *** GENERATED BY 'make hact-debug.ace' *** --" > hact-debug.ace
	$(GEPP) -DASSERTION $(ROOT_DIR)/hact.tpl - >> hact-debug.ace

hact.dep:
	$(ECHO) "" > hact.dep

ve.esd: $(ROOT_DIR)/ve.esd
	$(CP) $(ROOT_DIR)/ve.esd ve.esd
