-- system:     "Gobo Eiffel Libraries precompilation"
-- compiler:   "Visual Eiffel 3.1"
-- author:     "Eric Bezault <ericb@gobosoft.com>"
-- copyright:  "Copyright (c) 1999, Eric Bezault and others"
-- license:    "Eiffel Forum Freeware License v1 (see forum.txt)"
-- date:       "$Date$"
-- revision:   "$Revision$"

library Gobo

cluster

   [Gobo_project	"."] end
   [Gobo			"$GOBO/library"] end
   [Kernel			"$VE_Lib/Kernel"] end

option

   assertions on

end
