# system:     "Gobo Eiffel Lint"
# author:     "Eric Bezault <ericb@gobosoft.com>"
# copyright:  "Copyright (c) 2000, Eric Bezault and others"
# license:    "Eiffel Forum Freeware License v1 (see forum.txt)"
# date:       "$Date$"
# revision:   "$Revision$"


TARGET=gelint
ROOT_CLASS=GELINT
CREATION_ROUTINE=execute
ROOT_DIR=${GOBO}/src/gelint

include ${GOBO}/misc/platform.mk
include ${GOBO}/misc/eiffel.mk
