# system:     "concat2 getest example"
# author:     "Eric Bezault <ericb@gobosoft.com>"
# copyright:  "Copyright (c) 2001, Eric Bezault and others"
# license:    "Eiffel Forum Freeware License v1 (see forum.txt)"
# date:       "$Date$"
# revision:   "$Revision$"


TARGET=xconcat2
ROOT_CLASS=XCONCAT2
CREATION_ROUTINE=make
ROOT_DIR=${GOBO}/example/test/concat2

include ${GOBO}/misc/platform.mk
include ${GOBO}/misc/eiffel.mk
include ${GOBO}/misc/test.mk
