# system:     "Gobo Eiffel Lex: lexical analyzer generator"
# author:     "Eric Bezault <ericb@gobosoft.com>"
# copyright:  "Copyright (c) 2000, Eric Bezault and others"
# license:    "Eiffel Forum Freeware License v1 (see forum.txt)"
# date:       "$Date$"
# revision:   "$Revision$"


TARGET=gelex
ROOT_CLASS=GELEX
CREATION_ROUTINE=execute
ROOT_DIR=${GOBO}/src/gelex

include ${GOBO}/misc/platform.mk
include ${GOBO}/misc/eiffel.mk
