#
# Build Gobo tools.
#

parameters:
  - name: os
    type: string
    default: ''
  - name: c_compiler
    type: string
    default: ''
  - name: vm_image
    type: string
    default: ''

stages:
  - stage: ${{ parameters.os }}_${{ parameters.c_compiler }}_build
    dependsOn: []
    jobs:
      - job: ${{ parameters.os }}_${{ parameters.c_compiler }}_build
        pool:
          vmImage: ${{ parameters.vm_image }}
        variables:
          - name: GOBO_CLI_THREAD
            ${{ if startsWith( parameters.os, 'macos' ) }}: 
              value: 1
            ${{ else }}:
                value: 0
        steps:
          - pwsh: . "$(Build.Repository.LocalPath)/.cicd/build_ge.ps1" azure ${{ parameters.c_compiler }}
            name: build
          - publish: "$(Build.Repository.LocalPath)/bin"
            artifact: gobo_bin_${{ parameters.os }}_${{ parameters.c_compiler }}
          - publish: "$(Build.Repository.LocalPath)/tool/gec/backend/c/config/default.cfg"
            artifact: gobo_c_config_${{ parameters.os }}_${{ parameters.c_compiler }}
