# system:     "Gobo Eiffel Test"
# author:     "Eric Bezault <ericb@gobosoft.com>"
# copyright:  "Copyright (c) 2000, Eric Bezault and others"
# license:    "Eiffel Forum Freeware License v1 (see forum.txt)"
# date:       "$Date$"
# revision:   "$Revision$"


TARGET=getest
ROOT_CLASS=GETEST
CREATION_ROUTINE=execute
ROOT_DIR=${GOBO}/src/getest

include ${GOBO}/misc/platform.mk
include ${GOBO}/misc/eiffel.mk
