# system:     "System clock example"
# author:     "Eric Bezault <ericb@gobosoft.com>"
# copyright:  "Copyright (c) 2001, Eric Bezault and others"
# license:    "Eiffel Forum Freeware License v1 (see forum.txt)"
# date:       "$Date$"
# revision:   "$Revision$"


TARGET=clock
ROOT_CLASS=CLOCK
CREATION_ROUTINE=execute
ROOT_DIR=${GOBO}/example/time/system_clock

include ${GOBO}/misc/platform.mk
include ${GOBO}/misc/eiffel.mk
