-- generated
class XMLCONF_XMLTEST_FILES feature
xmltest_invalid_001_ent: STRING is "<!ELEMENT doc EMPTY>%R%N<!ENTITY %% e %"<!--%">%R%N%%e; -->%R%N"
xmltest_invalid_001: STRING is "<!DOCTYPE doc SYSTEM %"001.ent%">%R%N<doc></doc>%R%N"
xmltest_invalid_002_ent: STRING is "<!ENTITY %% e %"(#PCDATA%">%R%N<!ELEMENT doc %%e;)>%R%N"
xmltest_invalid_002: STRING is "<!DOCTYPE doc SYSTEM %"002.ent%">%R%N<doc></doc>%R%N"
xmltest_invalid_003_ent: STRING is "<!ENTITY %% e %"<!ELEMENT %">%R%N%%e; doc (#PCDATA)>%R%N"
xmltest_invalid_003: STRING is "<!DOCTYPE doc SYSTEM %"003.ent%">%R%N<doc></doc>%R%N"
xmltest_invalid_004_ent: STRING is "<!ENTITY %% e1 %"<!ELEMENT %">%R%N<!ENTITY %% e2 %">%">%R%N%%e1; doc (#PCDATA) %%e2;%R%N"
xmltest_invalid_004: STRING is "<!DOCTYPE doc SYSTEM %"004.ent%">%R%N<doc></doc>%R%N"
xmltest_invalid_005_ent: STRING is "<!ENTITY %% e %">%">%R%N<!ELEMENT doc (#PCDATA) %%e;%R%N"
xmltest_invalid_005: STRING is "<!DOCTYPE doc SYSTEM %"005.ent%">%R%N<doc></doc>%R%N"
xmltest_invalid_006_ent: STRING is "<!ENTITY %% e %"(#PCDATA)>%">%R%N<!ELEMENT doc %%e;%R%N"
xmltest_invalid_006: STRING is "<!DOCTYPE doc SYSTEM %"006.ent%">%R%N<doc></doc>%R%N"
xmltest_not_wf_ext_sa_001_ent: STRING is "&e;"
xmltest_not_wf_ext_sa_001: STRING is "<!DOCTYPE doc [%R%N<!ENTITY e SYSTEM %"001.ent%">%R%N]>%R%N<doc>&e;</doc>%R%N"
xmltest_not_wf_ext_sa_002_ent: STRING is "<?xml version=%"1.0%" standalone=%"yes%"?>%R%Ndata%R%N%R%N"
xmltest_not_wf_ext_sa_002: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N<!ENTITY e SYSTEM %"002.ent%">%R%N]>%R%N<doc>&e;</doc>%R%N"
xmltest_not_wf_ext_sa_003_ent: STRING is "<?xml version=%"1.0%"?><?xml version=%"1.0%"?>%R%Ndata%R%N"
xmltest_not_wf_ext_sa_003: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N<!ENTITY e SYSTEM %"003.ent%">%R%N]>%R%N<doc>&e;</doc>%R%N"
xmltest_not_wf_not_sa_001_ent: STRING is "<![ INCLUDE [%R%N<!ELEMENT doc (#PCDATA)>%R%N]>%R%N"
xmltest_not_wf_not_sa_001: STRING is "<!DOCTYPE doc SYSTEM %"001.ent%">%R%N<doc></doc>%R%N"
xmltest_not_wf_not_sa_002: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N<!ENTITY %% e %"<?xml version='1.0' encoding='UTF-8'?>%">%R%N%%e;%R%N]>%R%N<doc></doc>"
xmltest_not_wf_not_sa_003_ent: STRING is "<!ELEMENT doc (#PCDATA)>%R%N<![ IGNORE [%R%N"
xmltest_not_wf_not_sa_003: STRING is "<!DOCTYPE doc SYSTEM %"003.ent%">%R%N<doc></doc>%R%N"
xmltest_not_wf_not_sa_004_ent: STRING is "<!ELEMENT doc (#PCDATA)>%R%N<![ INCLUDE [%R%N"
xmltest_not_wf_not_sa_004: STRING is "<!DOCTYPE doc SYSTEM %"004.ent%">%R%N<doc></doc>%R%N"
xmltest_not_wf_not_sa_005_ent: STRING is "<!ELEMENT doc (#PCDATA)>%R%N%%e;%R%N"
xmltest_not_wf_not_sa_005: STRING is "<!DOCTYPE doc SYSTEM %"005.ent%">%R%N<doc></doc>%R%N"
xmltest_not_wf_not_sa_006_ent: STRING is "<![INCLUDE%R%N<!ELEMENT doc (#PCDATA)>%R%N]]>%R%N"
xmltest_not_wf_not_sa_006: STRING is "<!DOCTYPE doc SYSTEM %"006.ent%">%R%N<doc></doc>%R%N"
xmltest_not_wf_not_sa_007_ent: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N]>%R%N"
xmltest_not_wf_not_sa_007: STRING is "<!DOCTYPE doc SYSTEM %"007.ent%">%R%N<doc></doc>%R%N"
xmltest_not_wf_not_sa_008_ent: STRING is "<!ELEMENT doc ANY>%R%N<!ENTITY e %"100%%%">%R%N"
xmltest_not_wf_not_sa_008: STRING is "<!DOCTYPE doc SYSTEM %"008.ent%">%R%N<doc></doc>%R%N"
xmltest_not_wf_sa_001: STRING is "<doc>%R%N<doc%R%N?%R%N<a</a>%R%N</doc>%R%N"
xmltest_not_wf_sa_002: STRING is "<doc>%R%N<.doc></.doc>%R%N</doc>%R%N%R%N"
xmltest_not_wf_sa_003: STRING is "<doc><? ?></doc>%R%N"
xmltest_not_wf_sa_004: STRING is "<doc><?target some data></doc>%R%N"
xmltest_not_wf_sa_005: STRING is "<doc><?target some data?</doc>%R%N"
xmltest_not_wf_sa_006: STRING is "<doc><!-- a comment -- another --></doc>%R%N"
xmltest_not_wf_sa_007: STRING is "<doc>&amp no refc</doc>%R%N"
xmltest_not_wf_sa_008: STRING is "<doc>&.entity;</doc>%R%N"
xmltest_not_wf_sa_009: STRING is "<doc>&#RE;</doc>%R%N"
xmltest_not_wf_sa_010: STRING is "<doc>A & B</doc>%R%N"
xmltest_not_wf_sa_011: STRING is "<doc a1></doc>%R%N"
xmltest_not_wf_sa_012: STRING is "<doc a1=v1></doc>%R%N"
xmltest_not_wf_sa_013: STRING is "<doc a1=%"v1'></doc>%R%N"
xmltest_not_wf_sa_014: STRING is "<doc a1=%"<foo>%"></doc>%R%N"
xmltest_not_wf_sa_015: STRING is "<doc a1=></doc>%R%N"
xmltest_not_wf_sa_016: STRING is "<doc a1=%"v1%" %"v2%"></doc>%R%N"
xmltest_not_wf_sa_017: STRING is "<doc><![CDATA[</doc>%R%N"
xmltest_not_wf_sa_018: STRING is "<doc><![CDATA [ stuff]]></doc>%R%N"
xmltest_not_wf_sa_019: STRING is "<doc></>%R%N"
xmltest_not_wf_sa_020: STRING is "<doc a1=%"A & B%"></doc>%R%N"
xmltest_not_wf_sa_021: STRING is "<doc a1=%"a&b%"></doc>%R%N"
xmltest_not_wf_sa_022: STRING is "<doc a1=%"&#123:%"></doc>%R%N"
xmltest_not_wf_sa_023: STRING is "<doc 12=%"34%"></doc>%R%N"
xmltest_not_wf_sa_024: STRING is "<doc>%R%N<123></123>%R%N</doc>%R%N"
xmltest_not_wf_sa_025: STRING is "<doc>]]></doc>%R%N"
xmltest_not_wf_sa_026: STRING is "<doc>]]]></doc>%R%N"
xmltest_not_wf_sa_027: STRING is "<doc>%R%N<!-- abc%R%N</doc>%R%N"
xmltest_not_wf_sa_028: STRING is "<doc>%R%N<?a pi that is not closed%R%N</doc>%R%N%R%N"
xmltest_not_wf_sa_029: STRING is "<doc>abc]]]>def</doc>%R%N"
xmltest_not_wf_sa_030: STRING is "<doc>A form feed (%/12/) is not legal in data</doc>%R%N"
xmltest_not_wf_sa_031: STRING is "<doc><?pi a form feed (%/12/) is not allowed in a pi?></doc>%R%N"
xmltest_not_wf_sa_032: STRING is "<doc><!-- a form feed (%/12/) is not allowed in a comment --></doc>%R%N"
xmltest_not_wf_sa_033: STRING is "<doc>abc%/27/def</doc>%R%N"
xmltest_not_wf_sa_034: STRING is "<doc%/12/>A form-feed is not white space or a name character</doc%/12/>%R%N"
xmltest_not_wf_sa_035: STRING is "<doc>1 < 2 but not in XML</doc>%R%N"
xmltest_not_wf_sa_036: STRING is "<doc></doc>%R%NIllegal data%R%N"
xmltest_not_wf_sa_037: STRING is "<doc></doc>%R%N&#32;%R%N"
xmltest_not_wf_sa_038: STRING is "<doc x=%"foo%" y=%"bar%" x=%"baz%"></doc>%R%N"
xmltest_not_wf_sa_039: STRING is "<doc><a></aa></doc>%R%N"
xmltest_not_wf_sa_040: STRING is "<doc></doc>%R%N<doc></doc>%R%N"
xmltest_not_wf_sa_041: STRING is "<doc/>%R%N<doc></doc>%R%N"
xmltest_not_wf_sa_042: STRING is "<doc/></doc/>%R%N"
xmltest_not_wf_sa_043: STRING is "<doc/>%R%NIllegal data%R%N"
xmltest_not_wf_sa_044: STRING is "<doc/><doc/>%R%N"
xmltest_not_wf_sa_045: STRING is "<doc>%R%N<a/%R%N</doc>%R%N%R%N"
xmltest_not_wf_sa_046: STRING is "<doc>%R%N<a/</a>%R%N</doc>%R%N"
xmltest_not_wf_sa_047: STRING is "<doc>%R%N<a / >%R%N</doc>%R%N"
xmltest_not_wf_sa_048: STRING is "<doc>%R%N</doc>%R%N<![CDATA[]]>%R%N"
xmltest_not_wf_sa_049: STRING is "<doc>%R%N<a><![CDATA[xyz]]]></a>%R%N<![CDATA[]]></a>%R%N</doc>%R%N"
xmltest_not_wf_sa_051: STRING is "<!-- a comment -->%R%N<![CDATA[]]>%R%N<doc></doc>%R%N"
xmltest_not_wf_sa_052: STRING is "<!-- a comment -->%R%N&#32;%R%N<doc></doc>%R%N"
xmltest_not_wf_sa_053: STRING is "<doc></DOC>%R%N"
xmltest_not_wf_sa_054: STRING is "<!DOCTYPE doc [%R%N<!ENTITY foo PUBLIC %"some public id%">%R%N]>%R%N<doc></doc>%R%N"
xmltest_not_wf_sa_055: STRING is "<!DOCTYPE doc [%R%N<doc></doc>%R%N"
xmltest_not_wf_sa_056: STRING is "<!DOCTYPE doc -- a comment -- []>%R%N<doc></doc>%R%N"
xmltest_not_wf_sa_057: STRING is "<!DOCTYPE doc [%R%N<!ENTITY e %"whatever%" -- a comment -->%R%N]>%R%N<doc></doc>%R%N"
xmltest_not_wf_sa_058: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N<!ATTLIST doc a1 (foo,bar) #IMPLIED>%R%N]>%R%N<doc></doc>%R%N"
xmltest_not_wf_sa_059: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N<!ATTLIST doc a1 NMTOKEN v1>%R%N]>%R%N<doc></doc>%R%N"
xmltest_not_wf_sa_060: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N<!ATTLIST doc a1 NAME #IMPLIED>%R%N]>%R%N<doc></doc>%R%N"
xmltest_not_wf_sa_061: STRING is "<!DOCTYPE doc [%R%N<!ENTITY e PUBLIC %"whatever%"%"e.ent%">%R%N]>%R%N<doc></doc>%R%N"
xmltest_not_wf_sa_062: STRING is "<!DOCTYPE doc [%R%N<!ENTITY foo%"some text%">%R%N]>%R%N<doc></doc>%R%N"
xmltest_not_wf_sa_063: STRING is "<!DOCTYPE doc [%R%N<![INCLUDE[ ]]>%R%N]>%R%N<doc></doc>%R%N"
xmltest_not_wf_sa_064: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N<!ATTLIST e a1 CDATA%"foo%">%R%N]>%R%N<doc></doc>%R%N"
xmltest_not_wf_sa_065: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N<!ATTLIST doc a1(foo|bar) #IMPLIED>%R%N]>%R%N<doc></doc>%R%N"
xmltest_not_wf_sa_066: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N<!ATTLIST doc a1 (foo|bar)#IMPLIED>%R%N]>%R%N<doc></doc>%R%N"
xmltest_not_wf_sa_067: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N<!ATTLIST doc a1 (foo)%"foo%">%R%N]>%R%N<doc></doc>%R%N"
xmltest_not_wf_sa_068: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N<!ATTLIST doc a1 NOTATION(foo) #IMPLIED>%R%N]>%R%N<doc></doc>%R%N"
xmltest_not_wf_sa_069: STRING is "<!DOCTYPE doc [%R%N<!NOTATION eps SYSTEM %"eps.exe%">%R%N<!-- missing space before NDATA -->%R%N<!ENTITY foo SYSTEM %"foo.eps%"NDATA eps>%R%N]>%R%N<doc></doc>%R%N"
xmltest_not_wf_sa_070: STRING is "<!-- a comment ending with three dashes --->%R%N<doc></doc>%R%N"
xmltest_not_wf_sa_071: STRING is "<!DOCTYPE doc [%R%N<!ENTITY e1 %"&e2;%">%R%N<!ENTITY e2 %"&e3;%">%R%N<!ENTITY e3 %"&e1;%">%R%N]>%R%N<doc>&e1;</doc>%R%N"
xmltest_not_wf_sa_072: STRING is "<doc>&foo;</doc>%R%N"
xmltest_not_wf_sa_073: STRING is "<!DOCTYPE doc [%R%N<!ENTITY e %"whatever%">%R%N]>%R%N<doc>&f;</doc>%R%N"
xmltest_not_wf_sa_074: STRING is "<!DOCTYPE doc [%R%N<!ENTITY e %"</foo><foo>%">%R%N]>%R%N<doc>%R%N<foo>&e;</foo>%R%N</doc>%R%N"
xmltest_not_wf_sa_075: STRING is "<!DOCTYPE doc [%R%N<!ENTITY e1 %"&e2;%">%R%N<!ENTITY e2 %"&e3;%">%R%N<!ENTITY e3 %"&e1;%">%R%N]>%R%N<doc a=%"&e1;%"></doc>%R%N%R%N"
xmltest_not_wf_sa_076: STRING is "<doc a=%"&foo;%"></doc>%R%N"
xmltest_not_wf_sa_077: STRING is "<!DOCTYPE doc [%R%N<!ENTITY foo %"&bar;%">%R%N]>%R%N<doc a=%"&foo;%"></doc>%R%N"
xmltest_not_wf_sa_078: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N<!ATTLIST doc a CDATA %"&foo;%">%R%N]>%R%N<doc></doc>%R%N"
xmltest_not_wf_sa_079: STRING is "<!DOCTYPE doc [%R%N<!ENTITY e1 %"&e2;%">%R%N<!ENTITY e2 %"&e3;%">%R%N<!ENTITY e3 %"&e1;%">%R%N<!ELEMENT doc (#PCDATA)>%R%N<!ATTLIST doc a CDATA %"&e1;%">%R%N]>%R%N<doc></doc>%R%N"
xmltest_not_wf_sa_080: STRING is "<!DOCTYPE doc [%R%N<!ENTITY e1 %"&e2;%">%R%N<!ENTITY e2 %"&e3;%">%R%N<!ENTITY e3 %"&e1;%">%R%N<!ELEMENT doc (#PCDATA)>%R%N<!ATTLIST doc a CDATA #FIXED %"&e1;%">%R%N]>%R%N<doc></doc>%R%N"
xmltest_not_wf_sa_081: STRING is "<!DOCTYPE doc [%R%N<!ENTITY e SYSTEM %"nul%">%R%N]>%R%N<doc a=%"&e;%"></doc>%R%N"
xmltest_not_wf_sa_082: STRING is "<!DOCTYPE doc [%R%N<!ENTITY e SYSTEM %"nul%">%R%N<!ELEMENT doc (#PCDATA)>%R%N<!ATTLIST doc a CDATA %"&e;%">%R%N]>%R%N<doc></doc>%R%N"
xmltest_not_wf_sa_083: STRING is "<!DOCTYPE doc [%R%N<!ENTITY e SYSTEM %"nul%" NDATA n>%R%N]>%R%N<doc>&e;</doc>%R%N"
xmltest_not_wf_sa_084: STRING is "<!DOCTYPE doc [%R%N<!ENTITY e SYSTEM %"nul%" NDATA n>%R%N<!ELEMENT doc (#PCDATA)>%R%N<!ATTLIST doc a CDATA %"&e;%">%R%N]>%R%N<doc></doc>%R%N"
xmltest_not_wf_sa_085: STRING is "<!DOCTYPE doc PUBLIC %"[%" %"null.ent%">%R%N<doc></doc>%R%N"
xmltest_not_wf_sa_086: STRING is "<!DOCTYPE doc [%R%N<!ENTITY foo PUBLIC %"[%" %"null.xml%">%R%N]>%R%N<doc></doc>%R%N"
xmltest_not_wf_sa_087: STRING is "<!DOCTYPE doc [%R%N<!NOTATION foo PUBLIC %"[%" %"null.ent%">%R%N]>%R%N<doc></doc>%R%N"
xmltest_not_wf_sa_088: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N<!ATTLIST doc a CDATA #IMPLIED>%R%N<!ENTITY e '%"'>%R%N]>%R%N<doc a=%"&e;></doc>%R%N"
xmltest_not_wf_sa_089: STRING is "<!DOCTYPE doc [%R%N<!ENTITY %% foo SYSTEM %"foo.xml%" NDATA bar>%R%N]>%R%N<doc></doc>%R%N"
xmltest_not_wf_sa_090: STRING is "<!DOCTYPE doc [%R%N<!ENTITY e %"<foo a='&#60;'></foo>%">%R%N]>%R%N<doc>&e;</doc>%R%N"
xmltest_not_wf_sa_091: STRING is "<!DOCTYPE doc [%R%N<!NOTATION n SYSTEM %"n%">%R%N<!ENTITY %% foo SYSTEM %"foo.xml%" NDATA n>%R%N]>%R%N<doc></doc>%R%N"
xmltest_not_wf_sa_092: STRING is "<!DOCTYPE doc [%R%N<!ENTITY e %"<foo a='&#38;'></foo>%">%R%N]>%R%N<doc>&e;</doc>%R%N"
xmltest_not_wf_sa_093: STRING is "<doc>&#X58;</doc>%R%N"
xmltest_not_wf_sa_094: STRING is "<?xml VERSION=%"1.0%"?>%R%N<doc></doc>%R%N"
xmltest_not_wf_sa_095: STRING is "<?xml encoding=%"UTF-8%" version=%"1.0%"?>%R%N<doc></doc>%R%N"
xmltest_not_wf_sa_096: STRING is "<?xml version=%"1.0%"encoding=%"UTF-8%" ?>%R%N<doc></doc>"
xmltest_not_wf_sa_097: STRING is "<?xml version=%"1.0' encoding=%"UTF-8%" ?>%R%N<doc></doc>"
xmltest_not_wf_sa_098: STRING is "<?xml version=%"1.0%" version=%"1.0%"?>%R%N<doc></doc>"
xmltest_not_wf_sa_099: STRING is "<?xml version=%"1.0%" valid=%"no%" ?>%R%N<doc></doc>"
xmltest_not_wf_sa_100: STRING is "<?xml version=%"1.0%" standalone=%"YES%" ?>%R%N<doc></doc>%R%N"
xmltest_not_wf_sa_101: STRING is "<?xml version=%"1.0%" encoding=%" UTF-8%"?>%R%N<doc></doc>%R%N"
xmltest_not_wf_sa_102: STRING is "<?xml version=%"1.0 %" ?>%R%N<doc></doc>%R%N"
xmltest_not_wf_sa_103: STRING is "<!DOCTYPE doc [%R%N<!ENTITY e %"&#60;foo>%">%R%N]>%R%N<doc>&e;</doc>%R%N"
xmltest_not_wf_sa_104: STRING is "<!DOCTYPE doc [%R%N<!ENTITY e %"<foo>%">%R%N]>%R%N<doc>&e;</foo></doc>%R%N"
xmltest_not_wf_sa_105: STRING is "<?pi stuff?>%R%N<![CDATA[]]>%R%N<doc>%R%N</doc>%R%N"
xmltest_not_wf_sa_106: STRING is "<?pi data?>%R%N&#32;<doc></doc>%R%N"
xmltest_not_wf_sa_107: STRING is "<!DOCTYPE doc [%R%N<![CDATA[]]>%R%N]>%R%N<doc></doc>%R%N"
xmltest_not_wf_sa_108: STRING is "<doc>%R%N<![CDATA [  ]]>%R%N</doc>%R%N"
xmltest_not_wf_sa_109: STRING is "<!DOCTYPE doc [%R%N<!ENTITY e %"<doc></doc>%">%R%N]>%R%N&e;%R%N"
xmltest_not_wf_sa_110: STRING is "<!DOCTYPE doc [%R%N<!ENTITY e %"%">%R%N]>%R%N<doc></doc>%R%N&e;%R%N"
xmltest_not_wf_sa_111: STRING is "<!DOCTYPE doc [%R%N<!ENTITY e %"foo='bar'%">%R%N]>%R%N<doc &e;></doc>%R%N"
xmltest_not_wf_sa_112: STRING is "<doc>%R%N<![cdata[data]]>%R%N</doc>%R%N"
xmltest_not_wf_sa_113: STRING is "<!DOCTYPE doc [%R%N<!ENTITY %% foo %"&%">%R%N]>%R%N<doc></doc>%R%N"
xmltest_not_wf_sa_114: STRING is "<!DOCTYPE doc [%R%N<!ENTITY foo %"&%">%R%N]>%R%N<doc></doc>%R%N"
xmltest_not_wf_sa_115: STRING is "<!DOCTYPE doc [%R%N<!ENTITY e %"&#38;%">%R%N]>%R%N<doc a=%"&e;%"></doc>%R%N"
xmltest_not_wf_sa_116: STRING is "<!DOCTYPE doc [%R%N<!ENTITY e %"&#38;#9%">%R%N]>%R%N<doc>&e;7;</doc>%R%N"
xmltest_not_wf_sa_117: STRING is "<!DOCTYPE doc [%R%N<!ENTITY e %"&#38;%">%R%N]>%R%N<doc>&e;#97;</doc>%R%N"
xmltest_not_wf_sa_118: STRING is "<!DOCTYPE doc [%R%N<!ENTITY e %"#%">%R%N]>%R%N<doc>&&e;97;</doc>%R%N"
xmltest_not_wf_sa_119: STRING is "<!DOCTYPE doc [%R%N<!ENTITY e %"&#38;%">%R%N]>%R%N<doc>%R%N&e;#38;%R%N</doc>%R%N"
xmltest_not_wf_sa_120: STRING is "<!DOCTYPE doc [%R%N<!ENTITY e %"&#38;%">%R%N]>%R%N<doc>%R%N&e;%R%N</doc>%R%N"
xmltest_not_wf_sa_121: STRING is "<!DOCTYPE doc [%R%N<!ENTITY #DEFAULT %"default%">%R%N]>%R%N<doc></doc>%R%N"
xmltest_not_wf_sa_122: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (a, (b) | c)?>%R%N]>%R%N<doc></doc>%R%N"
xmltest_not_wf_sa_123: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc ((doc?)))>%R%N]>%R%N<doc></doc>%R%N"
xmltest_not_wf_sa_124: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (doc|#PCDATA)*>%R%N]>%R%N<doc></doc>%R%N"
xmltest_not_wf_sa_125: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc ((#PCDATA))>%R%N]>%R%N<doc></doc>%R%N"
xmltest_not_wf_sa_126: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)+>%R%N]>%R%N<doc></doc>%R%N"
xmltest_not_wf_sa_127: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)?>%R%N]>%R%N<doc></doc>%R%N"
xmltest_not_wf_sa_128: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc CDATA>%R%N]>%R%N<doc></doc>%R%N"
xmltest_not_wf_sa_129: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc - - (#PCDATA)>%R%N]>%R%N<doc></doc>%R%N"
xmltest_not_wf_sa_130: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (doc?) +(foo)>%R%N]>%R%N<doc></doc>%R%N"
xmltest_not_wf_sa_131: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (doc?) -(foo)>%R%N]>%R%N<doc></doc>%R%N"
xmltest_not_wf_sa_132: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (a, (b, c), (d, (e, f) | g))?>%R%N]>%R%N<doc></doc>%R%N"
xmltest_not_wf_sa_133: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (a *)>%R%N]>%R%N<doc></doc>%R%N"
xmltest_not_wf_sa_134: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (a) *>%R%N]>%R%N<doc></doc>%R%N"
xmltest_not_wf_sa_135: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (a & b)?>%R%N]>%R%N<doc></doc>%R%N"
xmltest_not_wf_sa_136: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc O O (#PCDATA)>%R%N]>%R%N<doc></doc>%R%N"
xmltest_not_wf_sa_137: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc(#PCDATA)>%R%N]>%R%N<doc></doc>%R%N"
xmltest_not_wf_sa_138: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (doc*?)>%R%N]>%R%N<doc></doc>%R%N"
xmltest_not_wf_sa_139: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc ()>%R%N]>%R%N<doc></doc>%R%N"
xmltest_not_wf_sa_140: STRING is "<!DOCTYPE doc [%R%N<!ENTITY e %"<&#x309a;></&#x309a;>%">%R%N]>%R%N<doc>&e;</doc>%R%N"
xmltest_not_wf_sa_141: STRING is "<!DOCTYPE doc [%R%N<!ENTITY e %"<X&#xe5c;></X&#xe5c;>%">%R%N]>%R%N<doc>&e;</doc>%R%N"
xmltest_not_wf_sa_142: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N]>%R%N<doc>&#0;</doc>%R%N"
xmltest_not_wf_sa_143: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N]>%R%N<doc>&#31;</doc>%R%N"
xmltest_not_wf_sa_144: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N]>%R%N<doc>&#xFFFF;</doc>%R%N"
xmltest_not_wf_sa_145: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N]>%R%N<doc>&#xD800;</doc>%R%N"
xmltest_not_wf_sa_146: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N]>%R%N<doc>&#x110000;</doc>%R%N"
xmltest_not_wf_sa_147: STRING is "%R%N<?xml version=%"1.0%"?>%R%N<doc></doc>%R%N"
xmltest_not_wf_sa_148: STRING is "<!-- -->%R%N<?xml version=%"1.0%"?>%R%N<doc></doc>%R%N"
xmltest_not_wf_sa_149: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N<?xml version=%"1.0%"?>%R%N]>%R%N<doc></doc>%R%N"
xmltest_not_wf_sa_150: STRING is "<doc>%R%N<?xml version=%"1.0%"?>%R%N</doc>%R%N"
xmltest_not_wf_sa_151: STRING is "<doc>%R%N</doc>%R%N<?xml version=%"1.0%"?>%R%N"
xmltest_not_wf_sa_152: STRING is "<?xml encoding=%"UTF-8%"?>%R%N<doc></doc>%R%N"
xmltest_not_wf_sa_153: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N<!ENTITY e %"<?xml encoding='UTF-8'?>%">%R%N]>%R%N<doc>&e;</doc>%R%N"
xmltest_not_wf_sa_154: STRING is "<?XML version=%"1.0%"?>%R%N<doc></doc>%R%N"
xmltest_not_wf_sa_155: STRING is "<?xmL version=%"1.0%"?>%R%N<doc></doc>%R%N"
xmltest_not_wf_sa_156: STRING is "<doc>%R%N<?xMl version=%"1.0%"?>%R%N</doc>%R%N"
xmltest_not_wf_sa_157: STRING is "<doc>%R%N<?xmL?>%R%N</doc>%R%N"
xmltest_not_wf_sa_158: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N<!NOTATION gif PUBLIC %"image/gif%" %"%">%R%N<!ATTLIST #NOTATION gif a1 CDATA #IMPLIED>%R%N]>%R%N<doc></doc>%R%N"
xmltest_not_wf_sa_159: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N<!ENTITY e %"<![CDATA[Tim & Michael]]>%">%R%N]>%R%N<doc>&e;</doc>%R%N"
xmltest_not_wf_sa_160: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N<!ENTITY %% e %"%">%R%N<!ENTITY foo %"%%e;%">%R%N]>%R%N<doc></doc>%R%N"
xmltest_not_wf_sa_161: STRING is "<!DOCTYPE doc [%R%N<!ENTITY %% e %"#PCDATA%">%R%N<!ELEMENT doc (%%e;)>%R%N]>%R%N<doc></doc>%R%N"
xmltest_not_wf_sa_162: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N<!ENTITY %% e1 %"%">%R%N<!ENTITY %% e2 %"%%e1;%">%R%N]>%R%N<doc></doc>%R%N"
xmltest_not_wf_sa_163: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N<!ENTITY %% e %"%">%R%N]>%R%N%%e;%R%N<doc></doc>%R%N"
xmltest_not_wf_sa_164: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N<!ENTITY %% e %"%">%R%N] %%e; >%R%N<doc></doc>%R%N"
xmltest_not_wf_sa_165: STRING is "<!DOCTYPE doc [%R%N<!ENTITY%% e %"%">%R%N<!ELEMENT doc (#PCDATA)>%R%N]>%R%N<doc></doc>%R%N"
xmltest_not_wf_sa_166: STRING is "<doc>%/239/%/191/%/191/</doc>%R%N"
xmltest_not_wf_sa_167: STRING is "<doc>%/239/%/191/%/190/</doc>%R%N"
xmltest_not_wf_sa_168: STRING is "<doc>%/237/%/160/%/128/</doc>%R%N"
xmltest_not_wf_sa_169: STRING is "<doc>%/237/%/176/%/128/</doc>%R%N"
xmltest_not_wf_sa_170: STRING is "<doc>%/247/%/128/%/128/%/128/</doc>%R%N"
xmltest_not_wf_sa_171: STRING is "<!-- %/239/%/191/%/191/ -->%R%N<doc></doc>%R%N"
xmltest_not_wf_sa_172: STRING is "<?pi %/239/%/191/%/191/?>%R%N<doc></doc>%R%N"
xmltest_not_wf_sa_173: STRING is "<doc a=%"%/239/%/191/%/191/%"></doc>%R%N"
xmltest_not_wf_sa_174: STRING is "<doc><![CDATA[%/239/%/191/%/191/]]></doc>%R%N"
xmltest_not_wf_sa_175: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N<!ENTITY %% e %"%/239/%/191/%/191/%">%R%N]>%R%N<doc></doc>%R%N"
xmltest_not_wf_sa_176: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N]>%R%N<doc>%R"
xmltest_not_wf_sa_177: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N]>%R%N<doc>A%/239/%/191/%/191/</doc>%R%N"
xmltest_not_wf_sa_178: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N<!ATTLIST doc a CDATA #IMPLIED>%R%N]>%R%N<doc a=%"&#34;></doc>%R%N"
xmltest_not_wf_sa_179: STRING is "<!DOCTYPE doc [%R%N<!ENTITY e %"&#34;>%R%N]>%R%N<doc></doc>%R%N"
xmltest_not_wf_sa_180: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N<!ATTLIST doc a CDATA %"&e;%">%R%N<!ENTITY e %"v%">%R%N]>%R%N<doc></doc>%R%N"
xmltest_not_wf_sa_181: STRING is "<!DOCTYPE doc [%R%N<!ENTITY e %"&#60;![CDATA[%">%R%N<!ELEMENT doc (#PCDATA)>%R%N]>%R%N<doc>&e;]]></doc>%R%N"
xmltest_not_wf_sa_182: STRING is "<!DOCTYPE doc [%R%N<!ENTITY e %"&#60;!--%">%R%N<!ELEMENT doc (#PCDATA)>%R%N]>%R%N<doc>&e;--></doc>%R%N"
xmltest_not_wf_sa_183: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA | foo*)* >%R%N<!ELEMENT foo EMPTY>%R%N]>%R%N<doc></doc>%R%N"
xmltest_not_wf_sa_184: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA | (foo))* >%R%N<!ELEMENT foo EMPTY>%R%N]>%R%N<doc></doc>%R%N%R%N"
xmltest_not_wf_sa_185_ent: STRING is "<!ELEMENT doc (#PCDATA)>%R%N"
xmltest_not_wf_sa_185: STRING is "<?xml version=%"1.0%" standalone=%"yes%"?>%R%N<!DOCTYPE doc SYSTEM %"185.ent%">%R%N<doc>&e;</doc>%R%N"
xmltest_not_wf_sa_186: STRING is "<!DOCTYPE a [%R%N<!ELEMENT a EMPTY>%R%N<!ATTLIST a b CDATA #IMPLIED d CDATA #IMPLIED>%R%N]>%R%N<a b=%"c%"d=%"e%"/>%R%N"
xmltest_valid_ext_sa_001_ent: STRING is "Data%R%N"
xmltest_valid_ext_sa_001: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N<!ENTITY e SYSTEM %"001.ent%">%R%N]>%R%N<doc>&e;</doc>%R%N"
xmltest_valid_ext_sa_002_ent: STRING is "Data"
xmltest_valid_ext_sa_002: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N<!ENTITY e SYSTEM %"002.ent%">%R%N]>%R%N<doc>&e;</doc>%R%N"
xmltest_valid_ext_sa_003: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N<!ENTITY e SYSTEM %"003.ent%">%R%N]>%R%N<doc>&e;</doc>%R%N"
xmltest_valid_ext_sa_004_ent: STRING is "Data%R"
xmltest_valid_ext_sa_004: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N<!ENTITY e SYSTEM %"004.ent%">%R%N]>%R%N<doc>&e;</doc>%R%N"
xmltest_valid_ext_sa_005_ent: STRING is "<e/><e/><e/>"
xmltest_valid_ext_sa_005: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (e*)>%R%N<!ELEMENT e EMPTY>%R%N<!ENTITY e SYSTEM %"005.ent%">%R%N]>%R%N<doc>&e;</doc>%R%N"
xmltest_valid_ext_sa_006_ent: STRING is "Data%R%N<e/>%R%NMore data%R%N<e/>%R%N"
xmltest_valid_ext_sa_006: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA|e)*>%R%N<!ELEMENT e EMPTY>%R%N<!ENTITY e SYSTEM %"006.ent%">%R%N]>%R%N<doc>&e;</doc>%R%N"
xmltest_valid_ext_sa_007_ent: STRING is
	once
			-- HACT does not support null characters in manifest strings.
		Result := "%/255/%/254/Y" + null
	end
xmltest_valid_ext_sa_007: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N<!ENTITY e SYSTEM %"007.ent%">%R%N]>%R%N<doc>X&e;Z</doc>%R%N"
xmltest_valid_ext_sa_008_ent: STRING is
	once
			-- HACT does not support null characters in manifest strings.
		Result := "%/255/%/254/<" + null + "?" + null + "x" + null + "m" + null + "l" + null + " " + null + "e" + null + "n" + null + "c" + null + "o" + null + "d" + null + "i" + null + "n" + null + "g" + null + "=" + null + "%"" + null + "U" + null + "T" + null + "F" + null + "-" + null + "1" + null + "6" + null + "%"" + null + "?" + null + ">" + null + "Y" + null
	end
xmltest_valid_ext_sa_008: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N<!ENTITY e SYSTEM %"008.ent%">%R%N]>%R%N<doc>X&e;Z</doc>%R%N"
xmltest_valid_ext_sa_009_ent: STRING is "%R"
xmltest_valid_ext_sa_009: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N<!ENTITY e SYSTEM %"009.ent%">%R%N]>%R%N<doc>&e;</doc>%R%N"
xmltest_valid_ext_sa_010: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N<!ENTITY e SYSTEM %"010.ent%">%R%N]>%R%N<doc>&e;</doc>%R%N"
xmltest_valid_ext_sa_011_ent: STRING is "xyzzy%R%N"
xmltest_valid_ext_sa_011: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N<!ENTITY e PUBLIC %"a not very interesting file%" %"011.ent%">%R%N]>%R%N<doc>&e;</doc>%R%N"
xmltest_valid_ext_sa_012_ent: STRING is "&e4;"
xmltest_valid_ext_sa_012: STRING is "<!DOCTYPE doc [%R%N<!ENTITY e1 %"&e2;%">%R%N<!ENTITY e2 %"&e3;%">%R%N<!ENTITY e3 SYSTEM %"012.ent%">%R%N<!ENTITY e4 %"&e5;%">%R%N<!ENTITY e5 %"(e5)%">%R%N<!ELEMENT doc (#PCDATA)>%R%N]>%R%N<doc>&e1;</doc>%R%N"
xmltest_valid_ext_sa_013_ent: STRING is "<e/>"
xmltest_valid_ext_sa_013: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (e)>%R%N<!ELEMENT e (#PCDATA)>%R%N<!ATTLIST e%R%N  a1 CDATA %"a1 default%"%R%N  a2 NMTOKENS %"a2 default%"%R%N>%R%N<!ENTITY x SYSTEM %"013.ent%">%R%N]>%R%N<doc>&x;</doc>%R%N"
xmltest_valid_ext_sa_014_ent: STRING is
	once
			-- HACT does not support null characters in manifest strings.
		Result := "%/255/%/254/%/255/%/254/d" + null + "a" + null + "t" + null + "a" + null
	end
xmltest_valid_ext_sa_014: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N<!ENTITY e SYSTEM %"014.ent%">%R%N]>%R%N<doc>&e;</doc>%R%N"
xmltest_valid_ext_sa_out_001: STRING is "<doc>Data&#10;</doc>"
xmltest_valid_ext_sa_out_002: STRING is "<doc>Data</doc>"
xmltest_valid_ext_sa_out_003: STRING is "<doc></doc>"
xmltest_valid_ext_sa_out_004: STRING is "<doc>Data&#10;</doc>"
xmltest_valid_ext_sa_out_005: STRING is "<doc><e></e><e></e><e></e></doc>"
xmltest_valid_ext_sa_out_006: STRING is "<doc>Data&#10;<e></e>&#10;More data&#10;<e></e>&#10;</doc>"
xmltest_valid_ext_sa_out_007: STRING is "<doc>XYZ</doc>"
xmltest_valid_ext_sa_out_008: STRING is "<doc>XYZ</doc>"
xmltest_valid_ext_sa_out_009: STRING is "<doc>&#10;</doc>"
xmltest_valid_ext_sa_out_010: STRING is "<doc></doc>"
xmltest_valid_ext_sa_out_011: STRING is "<doc>xyzzy&#10;</doc>"
xmltest_valid_ext_sa_out_012: STRING is "<doc>(e5)</doc>"
xmltest_valid_ext_sa_out_013: STRING is "<doc><e a1=%"a1 default%" a2=%"a2 default%"></e></doc>"
xmltest_valid_ext_sa_out_014: STRING is "<doc>%/239/%/187/%/191/data</doc>"
xmltest_valid_ext_sa_003_ent: STRING is ""
xmltest_valid_ext_sa_010_ent: STRING is ""
xmltest_valid_not_sa_001: STRING is "<!DOCTYPE doc SYSTEM %"001.ent%" [%R%N<!ELEMENT doc EMPTY>%R%N]>%R%N<doc></doc>%R%N"
xmltest_valid_not_sa_002_ent: STRING is "%R"
xmltest_valid_not_sa_002: STRING is "<!DOCTYPE doc SYSTEM %"002.ent%" [%R%N<!ELEMENT doc EMPTY>%R%N]>%R%N<doc></doc>%R%N"
xmltest_valid_not_sa_003_1_ent: STRING is "<!ELEMENT doc EMPTY>%R%N<!ENTITY %% e SYSTEM %"003-2.ent%">%R%N<!ATTLIST doc a1 CDATA %%e; %"v1%">%R%N"
xmltest_valid_not_sa_003: STRING is "<!DOCTYPE doc SYSTEM %"003-1.ent%">%R%N<doc></doc>%R%N"
xmltest_valid_not_sa_004_1_ent: STRING is "<!ELEMENT doc EMPTY>%R%N<!ENTITY %% e1 SYSTEM %"004-2.ent%">%R%N<!ENTITY %% e2 %"%%e1;%">%R%N%%e1;%R%N"
xmltest_valid_not_sa_004_2_ent: STRING is "<!ATTLIST doc a1 CDATA %"value%">%R%N"
xmltest_valid_not_sa_004: STRING is "<!DOCTYPE doc SYSTEM %"004-1.ent%">%R%N<doc></doc>%R%N"
xmltest_valid_not_sa_005_1_ent: STRING is "<!ELEMENT doc EMPTY>%R%N<!ENTITY %% e SYSTEM %"005-2.ent%">%R%N%%e;%R%N"
xmltest_valid_not_sa_005_2_ent: STRING is "<!ATTLIST doc a1 CDATA %"v1%">%R%N"
xmltest_valid_not_sa_005: STRING is "<!DOCTYPE doc SYSTEM %"005-1.ent%">%R%N<doc></doc>%R%N"
xmltest_valid_not_sa_006_ent: STRING is "<!ELEMENT doc EMPTY>%R%N<!ATTLIST doc a1 CDATA %"w1%" a2 CDATA %"w2%">%R%N"
xmltest_valid_not_sa_006: STRING is "<!DOCTYPE doc SYSTEM %"006.ent%" [%R%N<!ATTLIST doc a1 CDATA %"v1%">%R%N]>%R%N<doc></doc>%R%N"
xmltest_valid_not_sa_007_ent: STRING is "<!ELEMENT doc (#PCDATA)>%R%N<!ATTLIST doc a1 CDATA %"v1%">%R%N"
xmltest_valid_not_sa_007: STRING is "<!DOCTYPE doc SYSTEM %"007.ent%">%R%N<doc></doc>%R%N"
xmltest_valid_not_sa_008_ent: STRING is "<!ELEMENT doc (#PCDATA)>%R%N<!ATTLIST doc a1 CDATA %"v1%">%R%N"
xmltest_valid_not_sa_008: STRING is "<!DOCTYPE doc PUBLIC %"whatever%" %"008.ent%">%R%N<doc></doc>%R%N"
xmltest_valid_not_sa_009_ent: STRING is "<!ELEMENT doc (#PCDATA)>%R%N<!ATTLIST doc a1 CDATA %"v1%">%R%N"
xmltest_valid_not_sa_009: STRING is "<!DOCTYPE doc PUBLIC %"whatever%" %"009.ent%" [%R%N<!ATTLIST doc a2 CDATA %"v2%">%R%N]>%R%N<doc></doc>%R%N"
xmltest_valid_not_sa_010_ent: STRING is "<!ELEMENT doc (#PCDATA)>%R%N<!ATTLIST doc a1 CDATA %"v2%">%R%N"
xmltest_valid_not_sa_010: STRING is "<!DOCTYPE doc SYSTEM %"010.ent%" [%R%N<!ATTLIST doc a1 CDATA %"v1%">%R%N]>%R%N<doc></doc>%R%N"
xmltest_valid_not_sa_011_ent: STRING is "<!ELEMENT doc (#PCDATA)>%R%N<!ATTLIST doc a1 CDATA %"v1%">%R%N"
xmltest_valid_not_sa_011: STRING is "<!DOCTYPE doc [%R%N<!ENTITY %% e SYSTEM %"011.ent%">%R%N%%e;%R%N]>%R%N<doc></doc>%R%N"
xmltest_valid_not_sa_012_ent: STRING is "<?xml version=%"1.0%" encoding=%"UTF-8%"?>%R%N<!ELEMENT doc (#PCDATA)>%R%N<!ATTLIST doc a1 CDATA %"v1%">%R%N"
xmltest_valid_not_sa_012: STRING is "<!DOCTYPE doc [%R%N<!ENTITY %% e SYSTEM %"012.ent%">%R%N%%e;%R%N]>%R%N<doc></doc>%R%N"
xmltest_valid_not_sa_013_ent: STRING is "<!ELEMENT doc (#PCDATA)>%R%N<![ INCLUDE [%R%N<!ATTLIST doc a1 CDATA %"v1%">%R%N]]>%R%N"
xmltest_valid_not_sa_013: STRING is "<!DOCTYPE doc SYSTEM %"013.ent%">%R%N<doc></doc>%R%N"
xmltest_valid_not_sa_014_ent: STRING is "<!ELEMENT doc (#PCDATA)>%R%N<![ %%e; [%R%N<!ATTLIST doc a1 CDATA %"v1%">%R%N]]>%R%N"
xmltest_valid_not_sa_014: STRING is "<!DOCTYPE doc SYSTEM %"014.ent%" [%R%N<!ENTITY %% e %"INCLUDE%">%R%N]>%R%N<doc></doc>%R%N"
xmltest_valid_not_sa_015_ent: STRING is "<!ELEMENT doc (#PCDATA)>%R%N<![ %%e; [%R%N<!ATTLIST doc a1 CDATA %"v1%">%R%N]]>%R%N<!ATTLIST doc a2 CDATA %"v2%">%R%N"
xmltest_valid_not_sa_015: STRING is "<!DOCTYPE doc SYSTEM %"015.ent%" [%R%N<!ENTITY %% e %"IGNORE%">%R%N]>%R%N<doc></doc>%R%N"
xmltest_valid_not_sa_016_ent: STRING is "<!ELEMENT doc (#PCDATA)>%R%N<![%%e;[%R%N<!ATTLIST doc a1 CDATA %"v1%">%R%N]]>%R%N"
xmltest_valid_not_sa_016: STRING is "<!DOCTYPE doc SYSTEM %"016.ent%" [%R%N<!ENTITY %% e %"INCLUDE%">%R%N]>%R%N<doc></doc>%R%N"
xmltest_valid_not_sa_017_ent: STRING is "<!ELEMENT doc (#PCDATA)>%R%N<!ENTITY %% e %"<!ATTLIST doc a1 CDATA 'v1'>%">%R%N%%e;%R%N"
xmltest_valid_not_sa_017: STRING is "<!DOCTYPE doc SYSTEM %"017.ent%">%R%N<doc></doc>%R%N"
xmltest_valid_not_sa_018_ent: STRING is "<!ELEMENT doc (#PCDATA)>%R%N<!ENTITY %% e %"'v1'%">%R%N<!ATTLIST doc a1 CDATA %%e;>%R%N"
xmltest_valid_not_sa_018: STRING is "<!DOCTYPE doc SYSTEM %"018.ent%">%R%N<doc></doc>%R%N"
xmltest_valid_not_sa_019_ent: STRING is "<!ELEMENT doc (#PCDATA)>%R%N<!ENTITY %% e %"'v1'%">%R%N<!ATTLIST doc a1 CDATA%%e;>%R%N"
xmltest_valid_not_sa_019: STRING is "<!DOCTYPE doc SYSTEM %"019.ent%">%R%N<doc></doc>%R%N"
xmltest_valid_not_sa_020_ent: STRING is "<!ENTITY %% e %"doc%">%R%N<!ELEMENT doc (#PCDATA)>%R%N<!ATTLIST%%e;a1 CDATA %"v1%">%R%N"
xmltest_valid_not_sa_020: STRING is "<!DOCTYPE doc SYSTEM %"020.ent%">%R%N<doc></doc>%R%N"
xmltest_valid_not_sa_021_ent: STRING is "<!ENTITY %% e %"doc a1 CDATA%">%R%N<!ELEMENT doc (#PCDATA)>%R%N<!ATTLIST %%e; %"v1%">%R%N"
xmltest_valid_not_sa_021: STRING is "<!DOCTYPE doc SYSTEM %"021.ent%">%R%N<doc></doc>%R%N"
xmltest_valid_not_sa_022_ent: STRING is "<!ENTITY %% e %"INCLUDE[%">%R%N<!ELEMENT doc (#PCDATA)>%R%N<![ %%e; <!ATTLIST doc a1 CDATA %"v1%"> ]]>%R%N"
xmltest_valid_not_sa_022: STRING is "<!DOCTYPE doc SYSTEM %"022.ent%">%R%N<doc></doc>%R%N"
xmltest_valid_not_sa_023_ent: STRING is "<!ELEMENT doc (#PCDATA)>%R%N<!ENTITY %% e1 %"do%">%R%N<!ENTITY %% e2 %"c%">%R%N<!ENTITY %% e3 %"%%e1;%%e2;%">%R%N<!ATTLIST %%e3; a1 CDATA %"v1%">%R%N"
xmltest_valid_not_sa_023: STRING is "<!DOCTYPE doc SYSTEM %"023.ent%">%R%N<doc></doc>%R%N"
xmltest_valid_not_sa_024_ent: STRING is "<!ELEMENT doc (#PCDATA)>%R%N<!ENTITY %% e1 %"'v1'%">%R%N<!ENTITY %% e2 'a1 CDATA %%e1;'>%R%N<!ATTLIST doc %%e2;>%R%N"
xmltest_valid_not_sa_024: STRING is "<!DOCTYPE doc SYSTEM %"024.ent%">%R%N<doc></doc>%R%N"
xmltest_valid_not_sa_025_ent: STRING is "<!ELEMENT doc EMPTY>%R%N<!ENTITY %% e %"x%">%R%N<!ENTITY %% e %"y%">%R%N<!ENTITY %% v %"'%%e;'%">%R%N<!ATTLIST doc a1 CDATA %%v;>%R%N"
xmltest_valid_not_sa_025: STRING is "<!DOCTYPE doc SYSTEM %"025.ent%">%R%N<doc></doc>%R%N"
xmltest_valid_not_sa_026_ent: STRING is "<!ATTLIST doc a1 CDATA %"w1%">%R%N"
xmltest_valid_not_sa_026: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc ANY>%R%N<!ENTITY %% e SYSTEM %"026.ent%">%R%N%%e;%R%N<!ATTLIST doc a1 CDATA %"x1%" a2 CDATA %"x2%">%R%N]>%R%N<doc></doc>%R%N"
xmltest_valid_not_sa_027_ent: STRING is "<!ENTITY %% e %"%">%R%N<!ELEMENT doc (#PCDATA %%e;)>%R%N"
xmltest_valid_not_sa_027: STRING is "<!DOCTYPE doc SYSTEM %"027.ent%">%R%N<doc></doc>%R%N"
xmltest_valid_not_sa_028_ent: STRING is "<!ELEMENT doc (#PCDATA)>%R%N<![INCLUDE[<!ATTLIST doc a1 CDATA %"v1%">]]>%R%N"
xmltest_valid_not_sa_028: STRING is "<!DOCTYPE doc SYSTEM %"028.ent%">%R%N<doc></doc>%R%N"
xmltest_valid_not_sa_029_ent: STRING is "<!ELEMENT doc (#PCDATA)>%R%N<![IGNORE[<!ATTLIST doc a1 CDATA %"v1%">]]>%R%N<!ATTLIST doc a1 CDATA %"v2%">%R%N"
xmltest_valid_not_sa_029: STRING is "<!DOCTYPE doc SYSTEM %"029.ent%">%R%N<doc></doc>%R%N"
xmltest_valid_not_sa_030_ent: STRING is "<!ELEMENT doc (#PCDATA)>%R%N<![IGNORE[]]>%R%N<![INCLUDE[]]>%R%N"
xmltest_valid_not_sa_030: STRING is "<!DOCTYPE doc SYSTEM %"030.ent%">%R%N<doc></doc>%R%N"
xmltest_valid_not_sa_031_1_ent: STRING is "<!ELEMENT doc (#PCDATA)>%R%N<!ENTITY %% e SYSTEM %"031-2.ent%">%R%N<!ENTITY e %"<![CDATA[%%e;]]>%">%R%N"
xmltest_valid_not_sa_031_2_ent: STRING is "<!ATTLIST doc a1 CDATA %"v1%">%R%N"
xmltest_valid_not_sa_031: STRING is "<!DOCTYPE doc SYSTEM %"031-1.ent%">%R%N<doc>&e;</doc>%R%N"
xmltest_valid_not_sa_out_001: STRING is "<doc></doc>"
xmltest_valid_not_sa_out_002: STRING is "<doc></doc>"
xmltest_valid_not_sa_out_003: STRING is "<doc a1=%"v1%"></doc>"
xmltest_valid_not_sa_out_004: STRING is "<doc a1=%"value%"></doc>"
xmltest_valid_not_sa_out_005: STRING is "<doc a1=%"v1%"></doc>"
xmltest_valid_not_sa_out_006: STRING is "<doc a1=%"v1%" a2=%"w2%"></doc>"
xmltest_valid_not_sa_out_007: STRING is "<doc a1=%"v1%"></doc>"
xmltest_valid_not_sa_out_008: STRING is "<doc a1=%"v1%"></doc>"
xmltest_valid_not_sa_out_009: STRING is "<doc a1=%"v1%" a2=%"v2%"></doc>"
xmltest_valid_not_sa_out_010: STRING is "<doc a1=%"v1%"></doc>"
xmltest_valid_not_sa_out_011: STRING is "<doc a1=%"v1%"></doc>"
xmltest_valid_not_sa_out_012: STRING is "<doc a1=%"v1%"></doc>"
xmltest_valid_not_sa_out_013: STRING is "<doc a1=%"v1%"></doc>"
xmltest_valid_not_sa_out_014: STRING is "<doc a1=%"v1%"></doc>"
xmltest_valid_not_sa_out_015: STRING is "<doc a2=%"v2%"></doc>"
xmltest_valid_not_sa_out_016: STRING is "<doc a1=%"v1%"></doc>"
xmltest_valid_not_sa_out_017: STRING is "<doc a1=%"v1%"></doc>"
xmltest_valid_not_sa_out_018: STRING is "<doc a1=%"v1%"></doc>"
xmltest_valid_not_sa_out_019: STRING is "<doc a1=%"v1%"></doc>"
xmltest_valid_not_sa_out_020: STRING is "<doc a1=%"v1%"></doc>"
xmltest_valid_not_sa_out_021: STRING is "<doc a1=%"v1%"></doc>"
xmltest_valid_not_sa_out_022: STRING is "<doc a1=%"v1%"></doc>"
xmltest_valid_not_sa_out_023: STRING is "<doc a1=%"v1%"></doc>"
xmltest_valid_not_sa_out_024: STRING is "<doc a1=%"v1%"></doc>"
xmltest_valid_not_sa_out_025: STRING is "<doc a1=%"x%"></doc>"
xmltest_valid_not_sa_out_026: STRING is "<doc a1=%"w1%" a2=%"x2%"></doc>"
xmltest_valid_not_sa_out_027: STRING is "<doc></doc>"
xmltest_valid_not_sa_out_028: STRING is "<doc a1=%"v1%"></doc>"
xmltest_valid_not_sa_out_029: STRING is "<doc a1=%"v2%"></doc>"
xmltest_valid_not_sa_out_030: STRING is "<doc></doc>"
xmltest_valid_not_sa_out_031: STRING is "<doc>&lt;!ATTLIST doc a1 CDATA &quot;v1&quot;&gt;&#10;</doc>"
xmltest_valid_not_sa_001_ent: STRING is ""
xmltest_valid_sa_001: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N]>%R%N<doc></doc>%R%N"
xmltest_valid_sa_002: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N]>%R%N<doc ></doc>%R%N"
xmltest_valid_sa_003: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N]>%R%N<doc></doc >%R%N"
xmltest_valid_sa_004: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N<!ATTLIST doc a1 CDATA #IMPLIED>%R%N]>%R%N<doc a1=%"v1%"></doc>%R%N"
xmltest_valid_sa_005: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N<!ATTLIST doc a1 CDATA #IMPLIED>%R%N]>%R%N<doc a1 = %"v1%"></doc>%R%N"
xmltest_valid_sa_006: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N<!ATTLIST doc a1 CDATA #IMPLIED>%R%N]>%R%N<doc a1='v1'></doc>%R%N"
xmltest_valid_sa_007: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N]>%R%N<doc>&#32;</doc>%R%N"
xmltest_valid_sa_008: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N]>%R%N<doc>&amp;&lt;&gt;&quot;&apos;</doc>%R%N"
xmltest_valid_sa_009: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N]>%R%N<doc>&#x20;</doc>%R%N"
xmltest_valid_sa_010: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N<!ATTLIST doc a1 CDATA #IMPLIED>%R%N]>%R%N<doc a1=%"v1%" ></doc>%R%N"
xmltest_valid_sa_011: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N<!ATTLIST doc a1 CDATA #IMPLIED a2 CDATA #IMPLIED>%R%N]>%R%N<doc a1=%"v1%" a2=%"v2%"></doc>%R%N"
xmltest_valid_sa_012: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N<!ATTLIST doc : CDATA #IMPLIED>%R%N]>%R%N<doc :=%"v1%"></doc>%R%N"
xmltest_valid_sa_013: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N<!ATTLIST doc _.-0123456789 CDATA #IMPLIED>%R%N]>%R%N<doc _.-0123456789=%"v1%"></doc>%R%N"
xmltest_valid_sa_014: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N<!ATTLIST doc abcdefghijklmnopqrstuvwxyz CDATA #IMPLIED>%R%N]>%R%N<doc abcdefghijklmnopqrstuvwxyz=%"v1%"></doc>%R%N"
xmltest_valid_sa_015: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N<!ATTLIST doc ABCDEFGHIJKLMNOPQRSTUVWXYZ CDATA #IMPLIED>%R%N]>%R%N<doc ABCDEFGHIJKLMNOPQRSTUVWXYZ=%"v1%"></doc>%R%N"
xmltest_valid_sa_016: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N]>%R%N<doc><?pi?></doc>%R%N"
xmltest_valid_sa_017: STRING is
	once
			-- There is bug in SE -0.74 with ANSI C trigraphs (e.g. "??>" = "}").
		Result := "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N]>%R%N<doc><?pi some data ? > <?"+"?></doc>%R%N"
	end
xmltest_valid_sa_018: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N]>%R%N<doc><![CDATA[<foo>]]></doc>%R%N"
xmltest_valid_sa_019: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N]>%R%N<doc><![CDATA[<&]]></doc>%R%N"
xmltest_valid_sa_020: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N]>%R%N<doc><![CDATA[<&]>]]]></doc>%R%N"
xmltest_valid_sa_021: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N]>%R%N<doc><!-- a comment --></doc>%R%N"
xmltest_valid_sa_022: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N]>%R%N<doc><!-- a comment ->--></doc>%R%N"
xmltest_valid_sa_023: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N<!ENTITY e %"%">%R%N]>%R%N<doc>&e;</doc>%R%N"
xmltest_valid_sa_024: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (foo)>%R%N<!ELEMENT foo (#PCDATA)>%R%N<!ENTITY e %"&#60;foo></foo>%">%R%N]>%R%N<doc>&e;</doc>%R%N"
xmltest_valid_sa_025: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (foo*)>%R%N<!ELEMENT foo (#PCDATA)>%R%N]>%R%N<doc><foo/><foo></foo></doc>%R%N"
xmltest_valid_sa_026: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (foo*)>%R%N<!ELEMENT foo EMPTY>%R%N]>%R%N<doc><foo/><foo></foo></doc>%R%N"
xmltest_valid_sa_027: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (foo*)>%R%N<!ELEMENT foo ANY>%R%N]>%R%N<doc><foo/><foo></foo></doc>%R%N"
xmltest_valid_sa_028: STRING is "<?xml version=%"1.0%"?>%R%N<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N]>%R%N<doc></doc>%R%N"
xmltest_valid_sa_029: STRING is "<?xml version='1.0'?>%R%N<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N]>%R%N<doc></doc>%R%N"
xmltest_valid_sa_030: STRING is "<?xml version = %"1.0%"?>%R%N<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N]>%R%N<doc></doc>%R%N"
xmltest_valid_sa_031: STRING is "<?xml version='1.0' encoding=%"UTF-8%"?>%R%N<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N]>%R%N<doc></doc>%R%N"
xmltest_valid_sa_032: STRING is "<?xml version='1.0' standalone='yes'?>%R%N<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N]>%R%N<doc></doc>%R%N"
xmltest_valid_sa_033: STRING is "<?xml version='1.0' encoding=%"UTF-8%" standalone='yes'?>%R%N<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N]>%R%N<doc></doc>%R%N"
xmltest_valid_sa_034: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N]>%R%N<doc/>%R%N"
xmltest_valid_sa_035: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N]>%R%N<doc />%R%N"
xmltest_valid_sa_036: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N]>%R%N<doc></doc>%R%N<?pi data?>%R%N"
xmltest_valid_sa_037: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N]>%R%N<doc></doc>%R%N<!-- comment -->%R%N%R%N"
xmltest_valid_sa_038: STRING is "<!-- comment -->%R%N<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N]>%R%N<doc></doc>%R%N%R%N"
xmltest_valid_sa_039: STRING is "<?pi data?>%R%N<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N]>%R%N<doc></doc>%R%N"
xmltest_valid_sa_040: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N<!ATTLIST doc a1 CDATA #IMPLIED>%R%N]>%R%N<doc a1=%"&quot;&lt;&amp;&gt;&apos;%"></doc>%R%N"
xmltest_valid_sa_041: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N<!ATTLIST doc a1 CDATA #IMPLIED>%R%N]>%R%N<doc a1=%"&#65;%"></doc>%R%N"
xmltest_valid_sa_042: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N]>%R%N<doc>&#00000000000000000000000000000000065;</doc>%R%N"
xmltest_valid_sa_043: STRING is "<!DOCTYPE doc [%R%N<!ATTLIST doc a1 CDATA #IMPLIED>%R%N<!ELEMENT doc (#PCDATA)>%R%N]>%R%N<doc a1=%"foo%R%Nbar%"></doc>%R%N"
xmltest_valid_sa_044: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (e*)>%R%N<!ELEMENT e EMPTY>%R%N<!ATTLIST e a1 CDATA %"v1%" a2 CDATA %"v2%" a3 CDATA #IMPLIED>%R%N]>%R%N<doc>%R%N<e a3=%"v3%"/>%R%N<e a1=%"w1%"/>%R%N<e a2=%"w2%" a3=%"v3%"/>%R%N</doc>%R%N"
xmltest_valid_sa_045: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N<!ATTLIST doc a1 CDATA %"v1%">%R%N<!ATTLIST doc a1 CDATA %"z1%">%R%N]>%R%N<doc></doc>%R%N"
xmltest_valid_sa_046: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N<!ATTLIST doc a1 CDATA %"v1%">%R%N<!ATTLIST doc a2 CDATA %"v2%">%R%N]>%R%N<doc></doc>%R%N"
xmltest_valid_sa_047: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N]>%R%N<doc>X%R%NY</doc>%R%N"
xmltest_valid_sa_048: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N]>%R%N<doc>]</doc>%R%N"
xmltest_valid_sa_049: STRING is
	once
			-- HACT does not support null characters in manifest strings.
		Result := "%/255/%/254/<" + null + "!" + null + "D" + null + "O" + null + "C" + null + "T" + null + "Y" + null + "P" + null + "E" + null + " " + null + "d" + null + "o" + null + "c" + null + " " + null + "[" + null + "%R" + null + "%N" + null + "<" + null + "!" + null + "E" + null + "L" + null + "E" + null + "M" + null + "E" + null + "N" + null + "T" + null + " " + null + "d" + null + "o" + null + "c" + null + " " + null + "(" + null + "#" + null + "P" + null + "C" + null + "D" + null + "A" + null + "T" + null + "A" + null + ")" + null + ">" + null + "%R" + null + "%N" + null + "]" + null + ">" + null + "%R" + null + "%N" + null + "<" + null + "d" + null + "o" + null + "c" + null + ">" + null + "%/163/" + null + "<" + null + "/" + null + "d" + null + "o" + null + "c" + null + ">" + null + "%R" + null + "%N" + null
	end
xmltest_valid_sa_050: STRING is
	once
			-- HACT does not support null characters in manifest strings.
		Result := "%/255/%/254/<" + null + "!" + null + "D" + null + "O" + null + "C" + null + "T" + null + "Y" + null + "P" + null + "E" + null + " " + null + "d" + null + "o" + null + "c" + null + " " + null + "[" + null + "%R" + null + "%N" + null + "<" + null + "!" + null + "E" + null + "L" + null + "E" + null + "M" + null + "E" + null + "N" + null + "T" + null + " " + null + "d" + null + "o" + null + "c" + null + " " + null + "(" + null + "#" + null + "P" + null + "C" + null + "D" + null + "A" + null + "T" + null + "A" + null + ")" + null + ">" + null + "%R" + null + "%N" + null + "]" + null + ">" + null + "%R" + null + "%N" + null + "<" + null + "d" + null + "o" + null + "c" + null + ">" + null + "@%/14/%/8/%/14/!%/14/*%/14/L%/14/<" + null + "/" + null + "d" + null + "o" + null + "c" + null + ">" + null + "%R" + null + "%N" + null
	end
xmltest_valid_sa_051: STRING is
	once
			-- HACT does not support null characters in manifest strings.
		Result := "%/255/%/254/<" + null + "!" + null + "D" + null + "O" + null + "C" + null + "T" + null + "Y" + null + "P" + null + "E" + null + " " + null + "@%/14/%/8/%/14/!%/14/*%/14/L%/14/ " + null + "[" + null + "%R" + null + "%N" + null + "<" + null + "!" + null + "E" + null + "L" + null + "E" + null + "M" + null + "E" + null + "N" + null + "T" + null + " " + null + "@%/14/%/8/%/14/!%/14/*%/14/L%/14/ " + null + " " + null + "(" + null + "#" + null + "P" + null + "C" + null + "D" + null + "A" + null + "T" + null + "A" + null + ")" + null + ">" + null + "%R" + null + "%N" + null + "]" + null + ">" + null + "%R" + null + "%N" + null + "<" + null + "@%/14/%/8/%/14/!%/14/*%/14/L%/14/>" + null + "<" + null + "/" + null + "@%/14/%/8/%/14/!%/14/*%/14/L%/14/>" + null + "%R" + null + "%N" + null
	end
xmltest_valid_sa_052: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N]>%R%N<doc>%/240/%/144/%/128/%/128/%/244/%/143/%/191/%/189/</doc>%R%N"
xmltest_valid_sa_053: STRING is "<!DOCTYPE doc [%R%N<!ENTITY e %"<e/>%">%R%N<!ELEMENT doc (e)>%R%N<!ELEMENT e EMPTY>%R%N]>%R%N<doc>&e;</doc>%R%N"
xmltest_valid_sa_054: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N]>%R%N%R%N%R%N<doc%R%N></doc%R%N>%R%N%R%N%R%N"
xmltest_valid_sa_055: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N]>%R%N<?pi  data?>%R%N<doc></doc>%R%N"
xmltest_valid_sa_056: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N]>%R%N<doc>&#x0000000000000000000000000000000000000041;</doc>%R%N"
xmltest_valid_sa_057: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (a*)>%R%N]>%R%N<doc></doc>%R%N"
xmltest_valid_sa_058: STRING is "<!DOCTYPE doc [%R%N<!ATTLIST doc a1 NMTOKENS #IMPLIED>%R%N<!ELEMENT doc (#PCDATA)>%R%N]>%R%N<doc a1=%" 1  %T 2 %T %"></doc>%R%N"
xmltest_valid_sa_059: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (e*)>%R%N<!ELEMENT e EMPTY>%R%N<!ATTLIST e a1 CDATA #IMPLIED a2 CDATA #IMPLIED a3 CDATA #IMPLIED>%R%N]>%R%N<doc>%R%N<e a1=%"v1%" a2=%"v2%" a3=%"v3%"/>%R%N<e a1=%"w1%" a2=%"v2%"/>%R%N<e a1=%"v1%" a2=%"w2%" a3=%"v3%"/>%R%N</doc>%R%N"
xmltest_valid_sa_060: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N]>%R%N<doc>X&#10;Y</doc>%R%N"
xmltest_valid_sa_061: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N]>%R%N<doc>&#163;</doc>%R%N"
xmltest_valid_sa_062: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N]>%R%N<doc>&#xe40;&#xe08;&#xe21;%/224/%/184/%/170/%/224/%/185/%/140/</doc>%R%N"
xmltest_valid_sa_063: STRING is "<!DOCTYPE %/224/%/185/%/128/%/224/%/184/%/136/%/224/%/184/%/161/%/224/%/184/%/170/%/224/%/185/%/140/ [%R%N<!ELEMENT %/224/%/185/%/128/%/224/%/184/%/136/%/224/%/184/%/161/%/224/%/184/%/170/%/224/%/185/%/140/ (#PCDATA)>%R%N]>%R%N<%/224/%/185/%/128/%/224/%/184/%/136/%/224/%/184/%/161/%/224/%/184/%/170/%/224/%/185/%/140/></%/224/%/185/%/128/%/224/%/184/%/136/%/224/%/184/%/161/%/224/%/184/%/170/%/224/%/185/%/140/>%R%N"
xmltest_valid_sa_064: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N]>%R%N<doc>&#x10000;&#x10FFFD;</doc>%R%N"
xmltest_valid_sa_065: STRING is "<!DOCTYPE doc [%R%N<!ENTITY e %"&#60;%">%R%N<!ELEMENT doc (#PCDATA)>%R%N]>%R%N<doc></doc>%R%N"
xmltest_valid_sa_066: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N<!ATTLIST doc a1 CDATA #IMPLIED>%R%N<!-- 34 is double quote -->%R%N<!ENTITY e1 %"&#34;%">%R%N]>%R%N<doc a1=%"&e1;%"></doc>%R%N"
xmltest_valid_sa_067: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N]>%R%N<doc>&#13;</doc>%R%N"
xmltest_valid_sa_068: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N<!ENTITY e %"&#13;%">%R%N]>%R%N<doc>&e;</doc>%R%N"
xmltest_valid_sa_069: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N<!NOTATION n PUBLIC %"whatever%">%R%N]>%R%N<doc></doc>%R%N"
xmltest_valid_sa_070: STRING is "<!DOCTYPE doc [%R%N<!ENTITY %% e %"<!ELEMENT doc (#PCDATA)>%">%R%N%%e;%R%N]>%R%N<doc></doc>%R%N"
xmltest_valid_sa_071: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N<!ATTLIST doc a ID #IMPLIED>%R%N]>%R%N<doc></doc>%R%N"
xmltest_valid_sa_072: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N<!ATTLIST doc a IDREF #IMPLIED>%R%N]>%R%N<doc></doc>%R%N"
xmltest_valid_sa_073: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N<!ATTLIST doc a IDREFS #IMPLIED>%R%N]>%R%N<doc></doc>%R%N"
xmltest_valid_sa_074: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N<!ATTLIST doc a ENTITY #IMPLIED>%R%N]>%R%N<doc></doc>%R%N"
xmltest_valid_sa_075: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N<!ATTLIST doc a ENTITIES #IMPLIED>%R%N]>%R%N<doc></doc>%R%N"
xmltest_valid_sa_076: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N<!ATTLIST doc a NOTATION (n1|n2) #IMPLIED>%R%N<!NOTATION n1 SYSTEM %"http://www.w3.org/%">%R%N<!NOTATION n2 SYSTEM %"http://www.w3.org/%">%R%N]>%R%N<doc></doc>%R%N"
xmltest_valid_sa_077: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N<!ATTLIST doc a (1|2) #IMPLIED>%R%N]>%R%N<doc></doc>%R%N"
xmltest_valid_sa_078: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N<!ATTLIST doc a CDATA #REQUIRED>%R%N]>%R%N<doc a=%"v%"></doc>%R%N"
xmltest_valid_sa_079: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N<!ATTLIST doc a CDATA #FIXED %"v%">%R%N]>%R%N<doc a=%"v%"></doc>%R%N"
xmltest_valid_sa_080: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N<!ATTLIST doc a CDATA #FIXED %"v%">%R%N]>%R%N<doc></doc>%R%N"
xmltest_valid_sa_081: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (a, b, c)>%R%N<!ELEMENT a (a?)>%R%N<!ELEMENT b (b*)>%R%N<!ELEMENT c (a | b)+>%R%N]>%R%N<doc><a/><b/><c><a/></c></doc>%R%N"
xmltest_valid_sa_082: STRING is "<!DOCTYPE doc [%R%N<!ENTITY %% e SYSTEM %"e.dtd%">%R%N<!ELEMENT doc (#PCDATA)>%R%N]>%R%N<doc></doc>%R%N"
xmltest_valid_sa_083: STRING is "<!DOCTYPE doc [%R%N<!ENTITY %% e PUBLIC 'whatever' %"e.dtd%">%R%N<!ELEMENT doc (#PCDATA)>%R%N]>%R%N<doc></doc>%R%N"
xmltest_valid_sa_084: STRING is "<!DOCTYPE doc [<!ELEMENT doc (#PCDATA)>]><doc></doc>%R%N"
xmltest_valid_sa_085: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N<!ENTITY %% e %"<foo>%">%R%N<!ENTITY e %"%">%R%N]>%R%N<doc>&e;</doc>%R%N"
xmltest_valid_sa_086: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N<!ENTITY e %"%">%R%N<!ENTITY e %"<foo>%">%R%N]>%R%N<doc>&e;</doc>%R%N"
xmltest_valid_sa_087: STRING is "<!DOCTYPE doc [%R%N<!ENTITY e %"<foo/&#62;%">%R%N<!ELEMENT doc (foo)>%R%N<!ELEMENT foo EMPTY>%R%N]>%R%N<doc>&e;</doc>%R%N"
xmltest_valid_sa_088: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N<!ENTITY e %"&lt;foo>%">%R%N]>%R%N<doc>&e;</doc>%R%N"
xmltest_valid_sa_089: STRING is "<!DOCTYPE doc [%R%N<!ENTITY e %"&#x10000;&#x10FFFD;&#x10FFFF;%">%R%N<!ELEMENT doc (#PCDATA)>%R%N]>%R%N<doc>&e;</doc>%R%N"
xmltest_valid_sa_090: STRING is "<!DOCTYPE doc [%R%N<!ATTLIST e a NOTATION (n) #IMPLIED>%R%N<!ELEMENT doc (e)*>%R%N<!ELEMENT e (#PCDATA)>%R%N<!NOTATION n PUBLIC %"whatever%">%R%N]>%R%N<doc></doc>%R%N"
xmltest_valid_sa_091: STRING is "<!DOCTYPE doc [%R%N<!NOTATION n SYSTEM %"http://www.w3.org/%">%R%N<!ENTITY e SYSTEM %"http://www.w3.org/%" NDATA n>%R%N<!ELEMENT doc (#PCDATA)>%R%N<!ATTLIST doc a ENTITY %"e%">%R%N]>%R%N<doc></doc>%R%N"
xmltest_valid_sa_092: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (a)*>%R%N<!ELEMENT a EMPTY>%R%N]>%R%N<doc>%R%N<a/>%R%N    <a/>%T <a/>%R%N%R%N%R%N</doc>%R%N"
xmltest_valid_sa_093: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N]>%R%N<doc>%R%N%R%N%R%N</doc>%R"
xmltest_valid_sa_094: STRING is "<!DOCTYPE doc [%R%N<!ENTITY %% e %"foo%">%R%N<!ELEMENT doc (#PCDATA)>%R%N<!ATTLIST doc a1 CDATA %"%%e;%">%R%N]>%R%N<doc></doc>%R%N"
xmltest_valid_sa_095: STRING is "<!DOCTYPE doc [%R%N<!ATTLIST doc a1 CDATA #IMPLIED>%R%N<!ATTLIST doc a1 NMTOKENS #IMPLIED>%R%N<!ELEMENT doc (#PCDATA)>%R%N]>%R%N<doc a1=%"1  2%"></doc>%R%N"
xmltest_valid_sa_096: STRING is "<!DOCTYPE doc [%R%N<!ATTLIST doc a1 NMTOKENS %" 1  %T 2 %T %">%R%N<!ELEMENT doc (#PCDATA)>%R%N]>%R%N<doc></doc>%R%N"
xmltest_valid_sa_097_ent: STRING is "<!ATTLIST doc a2 CDATA #IMPLIED>%R%N"
xmltest_valid_sa_097: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N<!ENTITY %% e SYSTEM %"097.ent%">%R%N<!ATTLIST doc a1 CDATA %"v1%">%R%N%%e;%R%N<!ATTLIST doc a2 CDATA %"v2%">%R%N]>%R%N<doc></doc>%R%N"
xmltest_valid_sa_098: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N]>%R%N<doc><?pi x%R%Ny?></doc>%R%N"
xmltest_valid_sa_099: STRING is "<?xml version=%"1.0%" encoding=%"utf-8%"?>%R%N<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N]>%R%N<doc></doc>%R%N"
xmltest_valid_sa_100: STRING is "<!DOCTYPE doc [%R%N<!ENTITY e PUBLIC %";!*#@$_%%%" %"100.xml%">%R%N<!ELEMENT doc (#PCDATA)>%R%N]>%R%N<doc></doc>%R%N"
xmltest_valid_sa_101: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N<!ENTITY e %"&#34;%">%R%N]>%R%N<doc></doc>%R%N"
xmltest_valid_sa_102: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N<!ATTLIST doc a CDATA #IMPLIED>%R%N]>%R%N<doc a=%"&#34;%"></doc>%R%N"
xmltest_valid_sa_103: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N]>%R%N<doc>&#60;doc></doc>%R%N"
xmltest_valid_sa_104: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N<!ATTLIST doc a CDATA #IMPLIED>%R%N]>%R%N<doc a=%"x%Ty%"></doc>%R%N"
xmltest_valid_sa_105: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N<!ATTLIST doc a CDATA #IMPLIED>%R%N]>%R%N<doc a=%"x&#9;y%"></doc>%R%N"
xmltest_valid_sa_106: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N<!ATTLIST doc a CDATA #IMPLIED>%R%N]>%R%N<doc a=%"x&#10;y%"></doc>%R%N"
xmltest_valid_sa_107: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N<!ATTLIST doc a CDATA #IMPLIED>%R%N]>%R%N<doc a=%"x&#13;y%"></doc>%R%N"
xmltest_valid_sa_108: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N<!ENTITY e %"%R%N%">%R%N<!ATTLIST doc a CDATA #IMPLIED>%R%N]>%R%N<doc a=%"x&e;y%"></doc>%R%N"
xmltest_valid_sa_109: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N<!ATTLIST doc a CDATA #IMPLIED>%R%N]>%R%N<doc a=%"%"></doc>%R%N"
xmltest_valid_sa_110: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N<!ENTITY e %"&#13;&#10;%">%R%N<!ATTLIST doc a CDATA #IMPLIED>%R%N]>%R%N<doc a=%"x&e;y%"></doc>%R%N"
xmltest_valid_sa_111: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N<!ATTLIST doc a NMTOKENS #IMPLIED>%R%N]>%R%N<doc a=%"&#32;x&#32;&#32;y&#32;%"></doc>%R%N"
xmltest_valid_sa_112: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (a | b)>%R%N<!ELEMENT a (#PCDATA)>%R%N]>%R%N<doc><a></a></doc>%R%N"
xmltest_valid_sa_113: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N<!ATTLIST e a CDATA #IMPLIED>%R%N]>%R%N<doc></doc>%R%N"
xmltest_valid_sa_114: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N<!ENTITY e %"<![CDATA[&foo;]]>%">%R%N]>%R%N<doc>&e;</doc>%R%N"
xmltest_valid_sa_115: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N<!ENTITY e1 %"&e2;%">%R%N<!ENTITY e2 %"v%">%R%N]>%R%N<doc>&e1;</doc>%R%N"
xmltest_valid_sa_116: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N]>%R%N<doc><![CDATA[%R%N]]></doc>%R%N"
xmltest_valid_sa_117: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N<!ENTITY rsqb %"]%">%R%N]>%R%N<doc>&rsqb;</doc>%R%N"
xmltest_valid_sa_118: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc (#PCDATA)>%R%N<!ENTITY rsqb %"]]%">%R%N]>%R%N<doc>&rsqb;</doc>%R%N"
xmltest_valid_sa_119: STRING is "<!DOCTYPE doc [%R%N<!ELEMENT doc ANY>%R%N]>%R%N<doc><!-- -%/195/%/161/ --></doc>%R%N"
xmltest_valid_sa_out_001: STRING is "<doc></doc>"
xmltest_valid_sa_out_002: STRING is "<doc></doc>"
xmltest_valid_sa_out_003: STRING is "<doc></doc>"
xmltest_valid_sa_out_004: STRING is "<doc a1=%"v1%"></doc>"
xmltest_valid_sa_out_005: STRING is "<doc a1=%"v1%"></doc>"
xmltest_valid_sa_out_006: STRING is "<doc a1=%"v1%"></doc>"
xmltest_valid_sa_out_007: STRING is "<doc> </doc>"
xmltest_valid_sa_out_008: STRING is "<doc>&amp;&lt;&gt;&quot;'</doc>"
xmltest_valid_sa_out_009: STRING is "<doc> </doc>"
xmltest_valid_sa_out_010: STRING is "<doc a1=%"v1%"></doc>"
xmltest_valid_sa_out_011: STRING is "<doc a1=%"v1%" a2=%"v2%"></doc>"
xmltest_valid_sa_out_012: STRING is "<doc :=%"v1%"></doc>"
xmltest_valid_sa_out_013: STRING is "<doc _.-0123456789=%"v1%"></doc>"
xmltest_valid_sa_out_014: STRING is "<doc abcdefghijklmnopqrstuvwxyz=%"v1%"></doc>"
xmltest_valid_sa_out_015: STRING is "<doc ABCDEFGHIJKLMNOPQRSTUVWXYZ=%"v1%"></doc>"
xmltest_valid_sa_out_016: STRING is "<doc><?pi ?></doc>"
xmltest_valid_sa_out_017: STRING is
	once
			-- There is bug in SE -0.74 with ANSI C trigraphs (e.g. "??>" = "}").
		Result := "<doc><?pi some data ? > <?"+"?></doc>"
	end
xmltest_valid_sa_out_018: STRING is "<doc>&lt;foo&gt;</doc>"
xmltest_valid_sa_out_019: STRING is "<doc>&lt;&amp;</doc>"
xmltest_valid_sa_out_020: STRING is "<doc>&lt;&amp;]&gt;]</doc>"
xmltest_valid_sa_out_021: STRING is "<doc></doc>"
xmltest_valid_sa_out_022: STRING is "<doc></doc>"
xmltest_valid_sa_out_023: STRING is "<doc></doc>"
xmltest_valid_sa_out_024: STRING is "<doc><foo></foo></doc>"
xmltest_valid_sa_out_025: STRING is "<doc><foo></foo><foo></foo></doc>"
xmltest_valid_sa_out_026: STRING is "<doc><foo></foo><foo></foo></doc>"
xmltest_valid_sa_out_027: STRING is "<doc><foo></foo><foo></foo></doc>"
xmltest_valid_sa_out_028: STRING is "<doc></doc>"
xmltest_valid_sa_out_029: STRING is "<doc></doc>"
xmltest_valid_sa_out_030: STRING is "<doc></doc>"
xmltest_valid_sa_out_031: STRING is "<doc></doc>"
xmltest_valid_sa_out_032: STRING is "<doc></doc>"
xmltest_valid_sa_out_033: STRING is "<doc></doc>"
xmltest_valid_sa_out_034: STRING is "<doc></doc>"
xmltest_valid_sa_out_035: STRING is "<doc></doc>"
xmltest_valid_sa_out_036: STRING is "<doc></doc><?pi data?>"
xmltest_valid_sa_out_037: STRING is "<doc></doc>"
xmltest_valid_sa_out_038: STRING is "<doc></doc>"
xmltest_valid_sa_out_039: STRING is "<?pi data?><doc></doc>"
xmltest_valid_sa_out_040: STRING is "<doc a1=%"&quot;&lt;&amp;&gt;'%"></doc>"
xmltest_valid_sa_out_041: STRING is "<doc a1=%"A%"></doc>"
xmltest_valid_sa_out_042: STRING is "<doc>A</doc>"
xmltest_valid_sa_out_043: STRING is "<doc a1=%"foo bar%"></doc>"
xmltest_valid_sa_out_044: STRING is "<doc>&#10;<e a1=%"v1%" a2=%"v2%" a3=%"v3%"></e>&#10;<e a1=%"w1%" a2=%"v2%"></e>&#10;<e a1=%"v1%" a2=%"w2%" a3=%"v3%"></e>&#10;</doc>"
xmltest_valid_sa_out_045: STRING is "<doc a1=%"v1%"></doc>"
xmltest_valid_sa_out_046: STRING is "<doc a1=%"v1%" a2=%"v2%"></doc>"
xmltest_valid_sa_out_047: STRING is "<doc>X&#10;Y</doc>"
xmltest_valid_sa_out_048: STRING is "<doc>]</doc>"
xmltest_valid_sa_out_049: STRING is "<doc>%/194/%/163/</doc>"
xmltest_valid_sa_out_050: STRING is "<doc>%/224/%/185/%/128/%/224/%/184/%/136/%/224/%/184/%/161/%/224/%/184/%/170/%/224/%/185/%/140/</doc>"
xmltest_valid_sa_out_051: STRING is "<%/224/%/185/%/128/%/224/%/184/%/136/%/224/%/184/%/161/%/224/%/184/%/170/%/224/%/185/%/140/></%/224/%/185/%/128/%/224/%/184/%/136/%/224/%/184/%/161/%/224/%/184/%/170/%/224/%/185/%/140/>"
xmltest_valid_sa_out_052: STRING is "<doc>%/240/%/144/%/128/%/128/%/244/%/143/%/191/%/189/</doc>"
xmltest_valid_sa_out_053: STRING is "<doc><e></e></doc>"
xmltest_valid_sa_out_054: STRING is "<doc></doc>"
xmltest_valid_sa_out_055: STRING is "<?pi data?><doc></doc>"
xmltest_valid_sa_out_056: STRING is "<doc>A</doc>"
xmltest_valid_sa_out_057: STRING is "<doc></doc>"
xmltest_valid_sa_out_058: STRING is "<doc a1=%"1 2%"></doc>"
xmltest_valid_sa_out_059: STRING is "<doc>&#10;<e a1=%"v1%" a2=%"v2%" a3=%"v3%"></e>&#10;<e a1=%"w1%" a2=%"v2%"></e>&#10;<e a1=%"v1%" a2=%"w2%" a3=%"v3%"></e>&#10;</doc>"
xmltest_valid_sa_out_060: STRING is "<doc>X&#10;Y</doc>"
xmltest_valid_sa_out_061: STRING is "<doc>%/194/%/163/</doc>"
xmltest_valid_sa_out_062: STRING is "<doc>%/224/%/185/%/128/%/224/%/184/%/136/%/224/%/184/%/161/%/224/%/184/%/170/%/224/%/185/%/140/</doc>"
xmltest_valid_sa_out_063: STRING is "<%/224/%/185/%/128/%/224/%/184/%/136/%/224/%/184/%/161/%/224/%/184/%/170/%/224/%/185/%/140/></%/224/%/185/%/128/%/224/%/184/%/136/%/224/%/184/%/161/%/224/%/184/%/170/%/224/%/185/%/140/>"
xmltest_valid_sa_out_064: STRING is "<doc>%/240/%/144/%/128/%/128/%/244/%/143/%/191/%/189/</doc>"
xmltest_valid_sa_out_065: STRING is "<doc></doc>"
xmltest_valid_sa_out_066: STRING is "<doc a1=%"&quot;%"></doc>"
xmltest_valid_sa_out_067: STRING is "<doc>&#13;</doc>"
xmltest_valid_sa_out_068: STRING is "<doc>&#13;</doc>"
xmltest_valid_sa_out_069: STRING is "<!DOCTYPE doc [%N<!NOTATION n PUBLIC 'whatever'>%N]>%N<doc></doc>"
xmltest_valid_sa_out_070: STRING is "<doc></doc>"
xmltest_valid_sa_out_071: STRING is "<doc></doc>"
xmltest_valid_sa_out_072: STRING is "<doc></doc>"
xmltest_valid_sa_out_073: STRING is "<doc></doc>"
xmltest_valid_sa_out_074: STRING is "<doc></doc>"
xmltest_valid_sa_out_075: STRING is "<doc></doc>"
xmltest_valid_sa_out_076: STRING is "<!DOCTYPE doc [%N<!NOTATION n1 SYSTEM 'http://www.w3.org/'>%N<!NOTATION n2 SYSTEM 'http://www.w3.org/'>%N]>%N<doc></doc>"
xmltest_valid_sa_out_077: STRING is "<doc></doc>"
xmltest_valid_sa_out_078: STRING is "<doc a=%"v%"></doc>"
xmltest_valid_sa_out_079: STRING is "<doc a=%"v%"></doc>"
xmltest_valid_sa_out_080: STRING is "<doc a=%"v%"></doc>"
xmltest_valid_sa_out_081: STRING is "<doc><a></a><b></b><c><a></a></c></doc>"
xmltest_valid_sa_out_082: STRING is "<doc></doc>"
xmltest_valid_sa_out_083: STRING is "<doc></doc>"
xmltest_valid_sa_out_084: STRING is "<doc></doc>"
xmltest_valid_sa_out_085: STRING is "<doc></doc>"
xmltest_valid_sa_out_086: STRING is "<doc></doc>"
xmltest_valid_sa_out_087: STRING is "<doc><foo></foo></doc>"
xmltest_valid_sa_out_088: STRING is "<doc>&lt;foo&gt;</doc>"
xmltest_valid_sa_out_089: STRING is "<doc>%/240/%/144/%/128/%/128/%/244/%/143/%/191/%/189/%/244/%/143/%/191/%/191/</doc>"
xmltest_valid_sa_out_090: STRING is "<!DOCTYPE doc [%N<!NOTATION n PUBLIC 'whatever'>%N]>%N<doc></doc>"
xmltest_valid_sa_out_091: STRING is "<!DOCTYPE doc [%N<!NOTATION n SYSTEM 'http://www.w3.org/'>%N]>%N<doc a=%"e%"></doc>"
xmltest_valid_sa_out_092: STRING is "<doc>&#10;<a></a>&#10;    <a></a>&#9;<a></a>&#10;&#10;&#10;</doc>"
xmltest_valid_sa_out_093: STRING is "<doc>&#10;&#10;&#10;</doc>"
xmltest_valid_sa_out_094: STRING is "<doc a1=%"%%e;%"></doc>"
xmltest_valid_sa_out_095: STRING is "<doc a1=%"1  2%"></doc>"
xmltest_valid_sa_out_096: STRING is "<doc a1=%"1 2%"></doc>"
xmltest_valid_sa_out_097: STRING is "<doc a1=%"v1%"></doc>"
xmltest_valid_sa_out_098: STRING is "<doc><?pi x%R%Ny?></doc>"
xmltest_valid_sa_out_099: STRING is "<doc></doc>"
xmltest_valid_sa_out_100: STRING is "<doc></doc>"
xmltest_valid_sa_out_101: STRING is "<doc></doc>"
xmltest_valid_sa_out_102: STRING is "<doc a=%"&quot;%"></doc>"
xmltest_valid_sa_out_103: STRING is "<doc>&lt;doc&gt;</doc>"
xmltest_valid_sa_out_104: STRING is "<doc a=%"x y%"></doc>"
xmltest_valid_sa_out_105: STRING is "<doc a=%"x&#9;y%"></doc>"
xmltest_valid_sa_out_106: STRING is "<doc a=%"x&#10;y%"></doc>"
xmltest_valid_sa_out_107: STRING is "<doc a=%"x&#13;y%"></doc>"
xmltest_valid_sa_out_108: STRING is "<doc a=%"x y%"></doc>"
xmltest_valid_sa_out_109: STRING is "<doc a=%"%"></doc>"
xmltest_valid_sa_out_110: STRING is "<doc a=%"x  y%"></doc>"
xmltest_valid_sa_out_111: STRING is "<doc a=%"x y%"></doc>"
xmltest_valid_sa_out_112: STRING is "<doc><a></a></doc>"
xmltest_valid_sa_out_113: STRING is "<doc></doc>"
xmltest_valid_sa_out_114: STRING is "<doc>&amp;foo;</doc>"
xmltest_valid_sa_out_115: STRING is "<doc>v</doc>"
xmltest_valid_sa_out_116: STRING is "<doc>&#10;</doc>"
xmltest_valid_sa_out_117: STRING is "<doc>]</doc>"
xmltest_valid_sa_out_118: STRING is "<doc>]]</doc>"
xmltest_valid_sa_out_119: STRING is "<doc></doc>"

	null: STRING is
		once
				-- HACT does not support null characters in manifest strings.
			Result := "T"
			Result.put ('%U', 1)
		end

end
