# system:     "Gobo Eiffel Kernel Library Tester"
# author:     "Eric Bezault <ericb@gobosoft.com>"
# copyright:  "Copyright (c) 2001, Eric Bezault and others"
# license:    "Eiffel Forum Freeware License v1 (see forum.txt)"
# date:       "$Date$"
# revision:   "$Revision$"


TARGET=xkernel
ROOT_CLASS=XKERNEL
CREATION_ROUTINE=make
ROOT_DIR=${GOBO}/test/kernel

include ${GOBO}/misc/platform.mk
include ${GOBO}/misc/eiffel.mk
include ${GOBO}/misc/test.mk
