# system:     "VHPR-3 test #7"
# author:     "Eric Bezault <ericb@gobosoft.com>"
# copyright:  "Copyright (c) 2001, Eric Bezault and others"
# license:    "Eiffel Forum License v2 (see forum.txt)"
# date:       "$Date$"
# revision:   "$Revision$"


ROOT_DIR=${GOBO}/test/gelint/validity/vhpr3/test7

include ${GOBO}/misc/platform.mk
include ${GOBO}/misc/gelint.mk
