# system:     "concat1 getest example"
# author:     "Eric Bezault <ericb@gobosoft.com>"
# copyright:  "Copyright (c) 2001, Eric Bezault and others"
# license:    "Eiffel Forum Freeware License v1 (see forum.txt)"
# date:       "$Date$"
# revision:   "$Revision$"


TARGET=xconcat1
ROOT_CLASS=XCONCAT1
CREATION_ROUTINE=make
ROOT_DIR=${GOBO}/example/test/concat1

include ${GOBO}/misc/platform.mk
include ${GOBO}/misc/eiffel.mk
include ${GOBO}/misc/test.mk
