# system:     "Gobo Eiffel Structure Library Tester"
# author:     "Eric Bezault <ericb@gobosoft.com>"
# copyright:  "Copyright (c) 2000, Eric Bezault and others"
# license:    "Eiffel Forum Freeware License v1 (see forum.txt)"
# date:       "$Date$"
# revision:   "$Revision$"


TARGET=xstructure
ROOT_CLASS=XSTRUCTURE
CREATION_ROUTINE=make
ROOT_DIR=${GOBO}/test/structure

include ${GOBO}/misc/platform.mk
include ${GOBO}/misc/eiffel.mk
include ${GOBO}/misc/test.mk
