# system:     "Gobo Eiffel Yacc: syntactical analyzer generator"
# author:     "Eric Bezault <ericb@gobosoft.com>"
# copyright:  "Copyright (c) 2000, Eric Bezault and others"
# license:    "Eiffel Forum Freeware License v1 (see forum.txt)"
# date:       "$Date$"
# revision:   "$Revision$"


TARGET=geyacc
ROOT_CLASS=GEYACC
CREATION_ROUTINE=execute
ROOT_DIR=$(GOBO)/src/geyacc

include $(GOBO)/misc/platform.make
include $(GOBO)/misc/eiffel.make
