# system:     "VTBT test #7"
# author:     "Eric Bezault <ericb@gobosoft.com>"
# copyright:  "Copyright (c) 2001, Eric Bezault and others"
# license:    "MIT License"
# date:       "$Date$"
# revision:   "$Revision$"


ROOT_DIR=${GOBO}/test/gelint/validity/vtbt/test7

include ${GOBO}/misc/platform.mk
include ${GOBO}/misc/gelint.mk
