# system:     "VTBT test #6"
# author:     "Eric Bezault <ericb@gobosoft.com>"
# copyright:  "Copyright (c) 2001, Eric Bezault and others"
# license:    "Eiffel Forum Freeware License v1 (see forum.txt)"
# date:       "$Date$"
# revision:   "$Revision$"


ROOT_DIR=${GOBO}/test/gelint/validity/vtbt/test6

include ${GOBO}/misc/platform.mk
include ${GOBO}/misc/gelint.mk
